Fix usergroup permission
ZupIT/charlescd pull request #1001
Opened 2021-03-16 18:59 UTC by Leandroqo

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

## Results

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

### Request (if appropriate):
> Url: **POST** {{url}}/hello/{{hello-code}}

Payload:
```json
{
    "key" : "value"
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "key" :  "value"
}
```
### Screenshots (if appropriate):

2021-03-22 12:13 UTC, bCatanant requested changes

2021-03-22 12:13 UTC, bCatanant commented on ui/src/modules/Settings/Credentials/__tests__/Credentials.spec.tsx
> +  screen.debug()
Remove screen.debug()

2021-03-22 17:43 UTC, bCatanant approved these changes

2021-03-23 12:22 UTC, bCatanant approved these changes

2021-03-23 20:09 UTC, luanecavalcantizup commented on ui/src/core/components/Modal/Trigger/styled.ts
> +  margin: 20px 0 20px 0;
As confirmed with the UX (Jose Silva), the margins top and bottom of the text description of trigger modal is 20px.

2021-03-23 20:11 UTC, luanecavalcantizup commented on ui/src/core/components/Modal/Trigger/styled.ts
> +  margin-top: 0;
I removed the margin-top of the buttons to adjust the margins inside this modal.

2021-03-23 20:19 UTC, bCatanant submitted a review, later dismissed

2021-04-05 13:55 UTC, ifdouglas submitted a review, later dismissed

2021-05-04 18:38 UTC, luanecavalcantizup commented
blocked by pr #1108

2021-05-06 13:16 UTC, luanecavalcantizup commented
waiting to be tested

2021-05-11 19:22 UTC, bCatanant approved these changes

2021-05-11 19:22 UTC, merged