Feature task/authorization security filter
ZupIT/charlescd pull request #1009
Opened 2021-03-19 09:21 UTC by barbararochazup

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

## Results

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

### Request (if appropriate):
> Url: **POST** {{url}}/hello/{{hello-code}}

Payload:
```json
{
    "key" : "value"
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "key" :  "value"
}
```
### Screenshots (if appropriate):

2021-04-06 13:16 UTC, emiteze requested changes

2021-04-06 13:16 UTC, emiteze commented on gate/Makefile
> +				$(GORUN) $(VEND_PATH)/github.com/vektra/mockery/v2/main.go --all --dir ./internal/repository --output ./tests/unit/mocks/ --keeptree --case underscore
Why was this path changed?

2021-04-06 13:16 UTC, emiteze commented on gate/cmd/http.go
> +			authorization := v1.Group("/authorization")
Maybe /authorize would be a better path

2021-04-06 13:16 UTC, emiteze commented on gate/internal/repository/workspace_repository.go
> +const findUserPermissionsAtWorkspace = `
findUserPermissionsAtWorkspaceQuery would be a better name

2021-04-06 13:38 UTC, pedroborgeszup commented on gate/Makefile
> +				$(GORUN) $(VEND_PATH)/github.com/vektra/mockery/v2/main.go --all --dir ./internal/repository --output ./tests/unit/mocks/ --keeptree --case underscore
In tests we only use Repository mocks but we were mocking everything, generating unused mocks

2021-04-08 23:05 UTC, emiteze approved these changes

2021-04-09 15:05 UTC, arthurpuccizup commented on gate/internal/repository/models/permission.go
> +	CreatedAt *time.Time `json:"-"`
Why this json description? In theory the model structs will never get above the repository layer, so it's not being transformed to json

2021-04-09 15:05 UTC, arthurpuccizup commented on gate/internal/repository/workspace_repository.go
> +`
Query as constant

2021-04-12 19:34 UTC, monicaribeiro approved these changes

2021-04-12 19:35 UTC, merged