[GATE] Refactoring system_token workspace and adding all_workspace
ZupIT/charlescd pull request #1033
Opened 2021-04-09 20:12 UTC by pedroborgeszup

2021-04-09 22:16 UTC, monicaribeiro requested changes

2021-04-09 22:16 UTC, monicaribeiro commented on gate/internal/repository/models/workspace.go
> +	ID                      uuid.UUID
Why this id is uppercase?

2021-04-09 22:16 UTC, monicaribeiro commented on gate/internal/repository/models/user_group.go
> +	id        string
Put the attributes on cammel case.

2021-04-09 22:16 UTC, monicaribeiro commented on gate/internal/repository/workspace_repository.go
> +	FindWorkspacesBySystemTokenId(systemTokenId string) ([]domain.SimpleWorkspace, error)
```suggestion
	FindBySystemTokenId(systemTokenId string) ([]domain.SimpleWorkspace, error)
```

2021-04-09 22:16 UTC, monicaribeiro commented on gate/internal/repository/workspace_repository.go
> +		return []domain.SimpleWorkspace{}, handlePermissionError("Find all workspaces failed", "PermissionRepository.FindWorkspacesBySystemTokenId.Find", res.Error, logging.InternalError)
```suggestion
		return []domain.SimpleWorkspace{}, handlePermissionError("Find workspaces by system token id failed.", "PermissionRepository.FindBySystemTokenId.Find", res.Error, logging.InternalError)
```

2021-04-09 22:16 UTC, monicaribeiro commented on gate/internal/repository/workspace_repository.go
> +	select
```suggestion
	SELECT
		id,
		name,
		created_at
	FROM
		workspaces w
	INNER JOIN system_tokens_workspaces stw ON
		p.id = stw.workspace_id
	WHERE
		stw .system_token_id = ?
```

2021-04-09 22:16 UTC, monicaribeiro commented on gate/internal/use_case/authorization/authorize_system_token.go
> +	permissions, err := authorizeSystemToken.permissionRepository.FindPermissionsBySystemTokenId(systemToken.ID.String())
```suggestion
	permissions, err := authorizeSystemToken.permissionRepository.FindBySystemTokenId(systemToken.ID.String())
```

2021-04-09 22:16 UTC, monicaribeiro commented on gate/internal/use_case/system_token/create_system_token.go
> +	if len(workspaces) < len(input.Workspaces) {
Maybe we could compare the ids too.

2021-04-09 22:16 UTC, monicaribeiro commented on gate/internal/use_case/system_token/create_system_token_input.go
> +		ID:            uuid.New(),
We could put all the ids in cammel case.

2021-04-09 22:16 UTC, monicaribeiro commented on gate/tests/unit/utils/dummy_utils.go
> +			Name: "Workspace Name",
```suggestion
			Name: "Workspace Name 2",
```

2021-04-09 22:16 UTC, monicaribeiro commented on gate/tests/unit/utils/dummy_utils.go
> +			Name: "Workspace Name",
A different name can help sometimes in unit tests.

2021-04-12 14:32 UTC, barbararochazup commented on gate/internal/repository/models/workspace.go
> +	RegistryConfigurationId string
Ids (GitConfigurationId, CdConfigurationId, etc) -> Should it be uuid type?

2021-04-12 14:38 UTC, barbararochazup commented on gate/internal/use_case/system_token/create_system_token_input.go
> +		ID:            uuid.New(),
Its a good practice (convention). See "Initialisms" topics https://github.com/golang/go/wiki/CodeReviewComments

2021-04-12 14:39 UTC, barbararochazup commented on gate/resources/migrations/20210409114800_system_token_workspaces_table.down.sql
> +--     DROP COLUMN all_workspaces;
Should be commented?

2021-04-12 15:30 UTC, monicaribeiro commented on gate/internal/repository/models/user_group.go
> +	id        string
Ignore this commentttt!! lol https://github.com/golang/go/wiki/CodeReviewComments#initialisms

2021-04-12 15:30 UTC, monicaribeiro commented on gate/internal/repository/models/user_group.go
> +	id        string
Just put it as "ID"

2021-04-12 15:30 UTC, monicaribeiro commented on gate/internal/repository/models/workspace.go
> +	ID                      uuid.UUID
Answer https://github.com/golang/go/wiki/CodeReviewComments#initialisms

2021-04-12 19:41 UTC, barbararochazup approved these changes

2021-04-12 20:29 UTC, monicaribeiro approved these changes

2021-04-12 20:29 UTC, merged