[WIP] Operator tests fix
ZupIT/charlescd pull request #1094
Opened 2021-04-22 20:55 UTC by eliasalveszup

- Added validation on request to verify whether the specified namespace exists and is active
- FIxing 500 error when trying to access invalid github or gitlab chart url (changed to 400)

2021-04-22 21:18 UTC, eliasalveszup commented on install/helm-chart/templates/butler-cluster-role.yaml
> +- apiGroups:
This cluster role needs to be addes to allow butler to get information about any namespace at root level

2021-04-23 13:59 UTC, lucasbfernandes commented
Fix DCO

2021-04-23 14:03 UTC, lucasbfernandes requested changes

2021-04-23 14:03 UTC, lucasbfernandes commented on butler/src/app/v2/api/deployments/pipes/namespace-validation.pipe.ts
> +    if (response.body.status?.phase !== "Active") {
Use single quotes, otherwise lint will fail

2021-04-23 17:56 UTC, closed without merging

2021-04-23 17:57 UTC, eliasalveszup commented
Closed due to another PR with DCO fix