Handle template error
ZupIT/charlescd pull request #1107
Opened 2021-04-27 12:03 UTC by thallesfreitaszup

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

## Results

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

### Request (if appropriate):
> Url: **POST** {{url}}/hello/{{hello-code}}

Payload:
```json
{
    "key" : "value"
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "key" :  "value"
}
```
### Screenshots (if appropriate):

2021-04-27 14:04 UTC, lucasbfernandes requested changes

2021-04-27 14:04 UTC, lucasbfernandes commented on butler/src/app/v2/core/filters/http-exception.filter.ts
> +  }
Wouldn't be better to refactor all occurrences of this error structure instead of filtering them here?

2021-04-27 14:04 UTC, lucasbfernandes commented on butler/src/app/v2/core/filters/http-exception.filter.ts
> +    public message: string;
No semicolons. Run `npm run lint`

2021-04-27 14:04 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/github/github-repository.ts
> +          ] }
Indent. Run `npm run lint`

2021-04-27 14:10 UTC, thallesfreitaszup commented on butler/src/app/v2/core/filters/http-exception.filter.ts
> +  }
Yes, i will do it!

2021-04-28 12:03 UTC, leandrorodrigueszup approved these changes

2021-04-28 13:13 UTC, lucasbfernandes approved these changes

2021-04-28 13:16 UTC, merged