Enhancement/duplicated entities
ZupIT/charlescd pull request #1169
Opened 2021-05-06 15:19 UTC by barbararochazup

## Issue Description

Custom validator when create duplicated entities

2021-05-12 22:58 UTC, fandrade-zup requested changes
Looks good to me, but need to use plural in messages

2021-05-12 22:58 UTC, fandrade-zup commented on moove/web/src/main/resources/locale/messages.properties
> +duplicated.circle.name.error=You can not save two circle with the same name.
You need to use plural

duplicated.workspace.name.error=You can not save two **workspaces** with the same name.
￼duplicated.circle.name.error=You can not save two **circles** with the same name.

2021-05-13 13:36 UTC, barbararochazup commented on moove/web/src/main/resources/locale/messages.properties
> +duplicated.circle.name.error=You can not save two circle with the same name.
Done

2021-05-13 18:53 UTC, thallesfreitaszup approved these changes

2021-05-13 18:53 UTC, thallesfreitaszup commented on moove/api/src/main/kotlin/io/charlescd/moove/api/MooveExceptionHandler.kt
> +        return ErrorMessageResponse.of(MooveErrorCode.INTERNAL_SERVER_ERROR, ex.message?.also { ex.message } ?: "Internal Server Error")
`ex.message ?: "Internal Server Error" `  will not produce the same output?

2021-05-13 20:27 UTC, barbararochazup commented on moove/api/src/main/kotlin/io/charlescd/moove/api/MooveExceptionHandler.kt
> +        return ErrorMessageResponse.of(MooveErrorCode.INTERNAL_SERVER_ERROR, ex.message?.also { ex.message } ?: "Internal Server Error")
Sometimes message is null, this was causing a null pointer

2021-05-14 17:39 UTC, fandrade-zup approved these changes
LGTM

2021-05-14 17:41 UTC, merged