Bug-hunting/not allow delete default root user
ZupIT/charlescd pull request #1208
Opened 2021-05-11 19:50 UTC by thallesfreitaszup

## Description

not allow delete default user root charlesadmin

2021-05-11 20:04 UTC, emiteze requested changes

2021-05-11 20:04 UTC, emiteze commented on moove/commons/src/main/kotlin/io/charlescd/moove/commons/exceptions/ForbiddenExceptionLegacy.kt
> +class ForbiddenExceptionLegacy : RuntimeException("Forbidden!")
I don't think that this would be a ForbiddenException since authorization is verified by Envoy, and Moove assumes that everything he receives is deemed authorized. And this is also a business rule to our admin user, so probably the better exception here would be BusinessException

2021-05-11 20:04 UTC, emiteze commented on moove/legacy-moove/src/main/kotlin/io/charlescd/moove/legacy/moove/service/UserServiceLegacy.kt
> +            throw ForbiddenExceptionLegacy()
Same here

2021-05-12 12:40 UTC, thallesfreitaszup commented on moove/commons/src/main/kotlin/io/charlescd/moove/commons/exceptions/ForbiddenExceptionLegacy.kt
> +class ForbiddenExceptionLegacy : RuntimeException("Forbidden!")
Good point! done

2021-05-12 12:40 UTC, thallesfreitaszup commented on moove/legacy-moove/src/main/kotlin/io/charlescd/moove/legacy/moove/service/UserServiceLegacy.kt
> +            throw ForbiddenExceptionLegacy()
done!

2021-05-12 12:55 UTC, barbararochazup approved these changes

2021-05-12 13:06 UTC, emiteze approved these changes

2021-05-12 13:45 UTC, merged