Compass/undeploy plugin
ZupIT/charlescd pull request #1252
Opened 2021-05-19 11:45 UTC by gabrielleitezup

## Issue Description

Compass undeploy plugin based on metrics

2021-06-28 12:25 UTC, arthurpuccizup requested changes

2021-06-28 12:25 UTC, arthurpuccizup commented on compass/plugins/action/circleundeployment/mooveclient.go
> +func getCurrentDeploymentAtCircle(circleID, workspaceId, url string) (DeploymentResponse, error) {
This file could be merged with the mooveclient file in the deployment plugin folder and created a common file in a common folder

2021-07-08 14:33 UTC, SchumaiquerZup commented
falta review!

2021-07-12 17:32 UTC, barbararochazup approved these changes

2021-07-15 21:10 UTC, merged