Remove unused packages
ZupIT/charlescd pull request #1255
Opened 2021-05-20 14:04 UTC by luanecavalcantizup

- improve lodash import
- remove unused packages
- move some packages to dev dependencies

2021-05-20 14:24 UTC, bCatanant commented on ui/package.json
> +    "react-intersection-observer": "^8.31.0",
esse e usado somente para teste ?

2021-05-20 14:28 UTC, luanecavalcantizup commented on ui/package.json
> +    "react-intersection-observer": "^8.31.0",
sim, só pra testes

2021-05-20 15:11 UTC, bCatanant approved these changes

2021-05-20 17:28 UTC, Leandroqo requested changes

2021-05-20 17:28 UTC, Leandroqo commented on ui/package.json
> +    "jwt-decode": "^3.1.2",
we use it on auth utils

2021-05-20 17:28 UTC, Leandroqo commented on ui/package.json
>      "typescript": "^4.0.3"
we can moove typescript to dev dependency too

2021-05-20 17:28 UTC, Leandroqo commented on ui/package.json
> +    "react-cookies": "^0.1.1",
react-cookies should a dependency.

2021-05-20 18:03 UTC, luanecavalcantizup commented on ui/package.json
> +    "jwt-decode": "^3.1.2",
you mean `jest-fetch-mock`?

2021-05-20 18:04 UTC, luanecavalcantizup commented on ui/package.json
> +    "jwt-decode": "^3.1.2",
I removed @types/jwt-decode, because is deprecated and not needed anymore https://www.npmjs.com/package/@types/jwt-decode

2021-05-20 18:26 UTC, luanecavalcantizup commented on ui/package.json
>      "typescript": "^4.0.3"
done!

2021-05-20 18:40 UTC, bCatanant approved these changes

2021-05-20 18:41 UTC, Leandroqo commented on ui/package.json
> +    "jwt-decode": "^3.1.2",
I'm referring to the jwt-decode lib

2021-05-20 18:48 UTC, luanecavalcantizup commented on ui/package.json
> +    "jwt-decode": "^3.1.2",
I will undo to previour version

2021-05-20 19:13 UTC, luanecavalcantizup commented on ui/package.json
> +    "jwt-decode": "^3.1.2",
this package continues is in dependencies

2021-05-24 14:37 UTC, Leandroqo approved these changes

2021-05-24 14:48 UTC, merged