Security/mtls
ZupIT/charlescd pull request #1289
Opened 2021-06-07 14:18 UTC by thallesfreitaszup

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

## Results

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

### Request (if appropriate):
> Url: **POST** {{url}}/hello/{{hello-code}}

Payload:
```json
{
    "key" : "value"
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "key" :  "value"
}
```
### Screenshots (if appropriate):

2021-08-31 18:50 UTC, barbararochazup requested changes
Update headers from files .ts and .kt 

Copyright 2020, 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA

2021-08-31 19:05 UTC, lucasmachadozup submitted a review, later dismissed

2021-09-01 17:18 UTC, lucasmachadozup approved these changes

2021-09-02 14:02 UTC, barbararochazup approved these changes

2021-11-10 12:38 UTC, tiagoangelozup commented on install/mtls-job/templates/mtls-job.yaml
> +                    image: "thallesf/cert-tls-gen:0.2.5"
I believe it is important to hold the necessary container images and their sources within Charles' repositories

2021-11-10 16:30 UTC, thallesfreitaszup commented
opened on #1502

2021-11-10 16:30 UTC, closed without merging