Fix layout
ZupIT/charlescd pull request #1305
Opened 2021-06-11 21:35 UTC by luanecavalcantizup

Signed-off-by: Luane Aquino <luane.cavalcanti@zup.com.br>

## Solution

Fix ui layout in the Tab.

## Screenshot (before)
![bug-1](https://user-images.githubusercontent.com/74269773/121750963-b64fc480-cae3-11eb-998d-40dfd4cec798.png)

![image](https://user-images.githubusercontent.com/74269773/122053033-c0601480-cdbc-11eb-86f7-84b0c5d1a957.png)

## Screenshot (after)
![image](https://user-images.githubusercontent.com/74269773/122052749-66f7e580-cdbc-11eb-94bf-b9eeecb18f5a.png)

![image](https://user-images.githubusercontent.com/74269773/122052859-85f67780-cdbc-11eb-9ab1-8318b8261a86.png)

2021-06-14 12:40 UTC, ifdouglas requested changes

2021-06-14 12:40 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/index.tsx
> +          <Styled.ButtonWrapper>
I think we do not need this new wrapper, but we can apply the css fixes to `<Styled.Actions>`

2021-06-15 13:24 UTC, bCatanant approved these changes

2021-06-15 13:58 UTC, ifdouglas approved these changes

2021-06-15 18:28 UTC, merged