Add Navtabs to storybook
ZupIT/charlescd pull request #1315
Opened 2021-06-17 13:43 UTC by Leandroqo

2021-06-18 14:37 UTC, ifdouglas approved these changes

2021-06-18 14:38 UTC, ifdouglas requested changes
Acho que o stories do `Icon` não faz parte desse PR, confere?

2021-06-18 17:08 UTC, luanecavalcantizup approved these changes

2021-06-22 16:28 UTC, ifdouglas approved these changes

2021-06-22 17:20 UTC, merged