Component infinitescroll
ZupIT/charlescd pull request #1320
Opened 2021-06-18 19:12 UTC by luanecavalcantizup

under development

### Screenshots:
![image](https://user-images.githubusercontent.com/74269773/122606782-dcc7af80-d04f-11eb-835d-c9dea5cf744f.png)

2021-06-21 18:20 UTC, Leandroqo requested changes

2021-06-21 18:20 UTC, Leandroqo commented on ui/src/stories/InfiniteScroll/InfiniteScroll.stories.tsx
> +      description: 'This function returns new items to be shown in the list.',
i think the description should be:
```suggestion
      description: 'This function will be called as long as hasMore is true and when scroll is at the end.',
```

2021-06-21 18:46 UTC, Leandroqo approved these changes

2021-06-22 13:51 UTC, ifdouglas approved these changes

2021-06-22 13:53 UTC, merged