Access token UI - improvements
ZupIT/charlescd pull request #1332
Opened 2021-06-24 18:27 UTC by luanecavalcantizup

## Solution

- Show token name on copy, revoke and regenerate modals.

### Screenshots (if appropriate):

2021-07-05 14:40 UTC, Leandroqo requested changes

2021-07-05 14:40 UTC, Leandroqo commented on ui/public/mockServiceWorker.js
> +    ;(async function () {
remove ;

2021-07-05 17:48 UTC, Leandroqo approved these changes

2021-07-05 17:53 UTC, bCatanant approved these changes

2021-07-06 20:07 UTC, bCatanant approved these changes

2021-07-06 22:07 UTC, Leandroqo approved these changes

2021-07-07 14:09 UTC, bCatanant approved these changes

2021-07-07 14:38 UTC, merged