Changed auth's api to use hash instead crypto
ZupIT/charlescd pull request #1368
Opened 2021-07-13 20:34 UTC by Leandroqo

Signed-off-by: Leandro Queiroz <leandroqueiroz92@gmail.com>

## Issue Description
Encryption verification is taking too long. Resulting in request timeout

## Solution
Changed auth's api to use hash instead crypto

2021-07-15 17:12 UTC, monicaribeiro requested changes

2021-07-15 17:12 UTC, monicaribeiro commented on gate/internal/repository/system_token_repository.go
> +	UpdateRevoke(systemToken domain.SystemToken) error
I would suggest changing the class name to 'UpdateRevokedStatus' or 'RevokeSystemToken'.

2021-07-15 17:12 UTC, monicaribeiro commented on gate/internal/repository/system_token_repository.go
> +		return handleSystemTokenError("Update system token failed", "SystemTokenRepository.UpdateRevoke.Updates", res.Error, logging.InternalError)
```suggestion
		return handleSystemTokenError("Update system token failed", "SystemTokenRepository.UpdateRevoke.Update", res.Error, logging.InternalError)
```

* if the suggestion be applied to the method name, we need to remember to update here.

2021-07-15 17:12 UTC, monicaribeiro commented on gate/resources/migrations/20210405150000_encrypt_system_token_value.up.sql
> +ALTER TABLE system_tokens ADD token VARCHAR(64);
In this case, shouldn't we add another file to run the migration?

2021-07-15 21:00 UTC, barbararochazup requested changes
Add in all changed files in header

Copyright 2020, 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA

2021-07-28 18:24 UTC, monicaribeiro requested changes

2021-07-28 18:24 UTC, monicaribeiro commented on gate/resources/migrations/20210620143200_hash_system_token.up.sql
> +ALTER TABLE system_tokens
Do we have to add the license header here? @barbararochazup

2021-07-28 18:28 UTC, monicaribeiro submitted a review, later dismissed

2021-08-02 17:01 UTC, barbararochazup submitted a review, later dismissed

2021-08-27 16:51 UTC, guilhermemartinsdeoliveirazup submitted a review, later dismissed
PR reviewed with Barbara Rossalli.

2021-09-16 13:51 UTC, thallesfreitaszup approved these changes

2021-09-16 14:05 UTC, guilhermemartinsdeoliveirazup approved these changes

2021-09-16 14:06 UTC, merged