Updated README and CONTRIBUTING
ZupIT/charlescd pull request #1418
Opened 2021-09-16 19:19 UTC by jessica-tw

Signed-off-by: jessica.olinda@zup.com.br <jessica.olinda@zup.com.br>

## Issue Description: 
README.md and the CONTRIBUTING guide were not according to the new template.

## Solution

Updated the README.md and the CONTRIBUTING guide according to the new templates.

2021-09-19 12:46 UTC, otaviojava approved these changes

2021-09-21 10:57 UTC, otaviojava commented
It looks ok to me.

2021-09-23 18:28 UTC, mdcpmoreira reviewed
Few text adjustements

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
>  You should configure a pre-commit Githook in your local machine, it will help you not commit files without a license header. Please check out [more about Githooks](https://github.com/ZupIT/charlescd/
```suggestion
You should configure a pre-commit Githook in your local machine, so it will help you not commit files without a license header. Please check out [more about Githooks](https://github.com/ZupIT/charlescd/blob/main/hooks/README.md).
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
>  When you commit use the ```**-S** ``` option to include the signing.
```suggestion
When you commit, use the ```**-S** ``` option to include the signing. 
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +1. Bugfixes need to include a test proving the existence of the bug and why you are fixing it, if it doesn't include, it will return to the sender.
```suggestion
1. Bugfixes need to include a test proving the existence of the bug and why you are fixing it. If it doesn't include, it will return to the sender.
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +2. New features need to include a test that proves it actually works, if it doesn't include, it will return to the sender.
```suggestion
2. New features need to include a test that proves it actually works. If it doesn't include, it will return to the sender.
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +If your collaboration changes the way we use any CharlesCD functionality, you should  also update the documentation.
```suggestion
If your collaboration changes the way we use any CharlesCD functionality, you should also update the documentation.
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +To ensure CharlesCD is always stable, **all submissions must go through our CI pipeline.** This is part of the process of making changes and includes everyone, even CharlesCD core team members.
```suggestion
**All submissions must go through our CI pipeline** in order to ensure CharlesCD is always stable. This is part of the process of making changes and includes everyone, even CharlesCD core team members. 
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +- **CharlesCD CI is based on GitHub Actions:** you are able to execute it on your own fork too and all pushes or pull requests to the main branch will be checked.
```suggestion
- **CharlesCD CI is based on GitHub Actions** so you are able to execute it on your own fork too and all pushes or pull requests to the main branch will be checked. 
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +After forking CharlesCD repo: Go to ’Actions’ tab (on your own fork) and push the big green button. That’s it!
```suggestion
After forking CharlesCD repo, you must go to ’Actions’ tab (on your own fork) and push the big green button. That’s it!
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +**Step 1:** When the commit changes box opens, add
```suggestion
**Step 1:** When the commit changes box opens, add the following command:
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +CharlesCD has many modules. The environment settings are different between them. Check the configuration documentation for each module.
```suggestion
CharlesCD has many modules and the environment settings are different between them. So, you should check the configuration documentation for each module.
```

2021-09-23 18:28 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +1. Check out if you’re on the latest version. If you’re not your problem may have been solved already.
```suggestion
1. Check out if you are on the latest version. If you’re not, your problem may have been solved already.
```

2021-09-23 18:37 UTC, jessica-tw commented on CONTRIBUTING.md
> +To ensure CharlesCD is always stable, **all submissions must go through our CI pipeline.** This is part of the process of making changes and includes everyone, even CharlesCD core team members.
I would remove 'in order to', maybe:

**All submissions must go through our CI pipeline** to ensure CharlesCD is always stable.

2021-09-27 16:39 UTC, barbararochazup requested changes
Could you please sign off the commits?

2021-09-27 16:57 UTC, barbararochazup requested changes

2021-09-27 16:57 UTC, barbararochazup commented on CONTRIBUTING.md
> +You can suggest a change in CharlesCD's developer discussion [**mailing list**](https://groups.google.com/forum/#!forum/charlescd-dev) or in our [**chat**](https://spectrum.chat/charlescd?tab=posts).
Mailing list and chat is deprecated, the official channel is our forum https://forum.zup.com.br/

2021-09-27 16:57 UTC, barbararochazup commented on CONTRIBUTING.md
> +- Ask any question about CharlesCD in our [**mailing list**](https://groups.google.com/forum/#!forum/charlescd-dev)
Mailing list is deprecated

2021-09-27 16:57 UTC, barbararochazup commented on CONTRIBUTING.md
> +- [**Butler**](https://github.com/ZupIT/charlescd/tree/main/butler)
Add other modules:

Hermes
Gate
UI

2021-09-28 18:52 UTC, jessica-tw commented on CONTRIBUTING.md
> +- [**Butler**](https://github.com/ZupIT/charlescd/tree/main/butler)
done!

2021-09-28 18:52 UTC, jessica-tw commented on CONTRIBUTING.md
> +You can suggest a change in CharlesCD's developer discussion [**mailing list**](https://groups.google.com/forum/#!forum/charlescd-dev) or in our [**chat**](https://spectrum.chat/charlescd?tab=posts).
done

2021-09-28 19:20 UTC, jessica-tw commented
> Could you please sign off the commits?

done :)

2021-09-28 19:20 UTC, jessica-tw commented
> Could you please sign off the commits?
Done

2021-09-29 14:14 UTC, barbararochazup approved these changes

2021-09-30 12:02 UTC, tiagoangelozup commented on README.md
> +5. By default, a module called `octopipe` is already in Charles' installation. This is a native platform created by our team to make installation easier, without previous configurations. However, you
I think that `octopipe` isn't used anymore. Right?

2021-11-16 21:19 UTC, mdcpmoreira approved these changes
@jessica-tw I reviewed both files! Specifically on the README, I put a suggestion to include the modules list of CharlesCD because I considered that, if someone is reading about the project for the first time, it'd be interesting to give this quick context. Let me know if it makes sense. :)

2021-11-16 21:19 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +**Step 3.** ```cd charlescd ```
```suggestion
**Step 3.** Run the command ```cd charlescd ```
```

2021-11-16 21:19 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +- You can ask question and chat with us in our [**forum**](https://forum.zup.com.br/c/en/charles/13).
```suggestion
- Do you have any question about CharlesCD? Let's chat in our [**forum**](https://forum.zup.com.br/c/en/charles/13).
```

2021-11-16 21:19 UTC, mdcpmoreira commented on README.md
> +4. A **Redis** to be used by `charlescd-circle-matcher`;
```suggestion
4. A **Redis** to be used by Circle Matcher module (`charlescd-circle-matcher`);
```

2021-11-16 21:19 UTC, mdcpmoreira commented on README.md
> +5. A **RabbitMQ** for `charlescd-hermes` use.
```suggestion
5. A **RabbitMQ** for `charlescd-hermes` module's use.
```

2021-11-16 21:19 UTC, mdcpmoreira commented on README.md
> +If you have any questions or ideas, let's chat in our [**forum**](https://forum.zup.com.br/c/en/charles/13).
```suggestion
Do you have any question or suggestion about Charles? Let's chat in our [**forum**](https://forum.zup.com.br/c/en/charles/13).
```

2021-11-16 21:19 UTC, mdcpmoreira commented on README.md
Currently, CharlesCD works with these modules: 

- [**Butler**](https://github.com/ZupIT/charlescd/tree/main/butler)
- [**Circle-Matcher**](https://github.com/ZupIT/charlescd/tree/main/circle-matcher)
- [**Compass**](https://github.com/ZupIT/charlescd/tree/main/compass)
- [**Gate**](https://github.com/ZupIT/charlescd/tree/main/gate)
- [**Hermes**](https://github.com/ZupIT/charlescd/tree/main/hermes)
- [**Moove**](https://github.com/ZupIT/charlescd/tree/main/moove)
- [**UI**](https://github.com/ZupIT/charlescd/tree/main/ui)
- [**Villager**](https://github.com/ZupIT/charlescd/tree/main/villager)

2021-11-16 21:46 UTC, jessica-tw commented
> @jessica-tw I reviewed both files! Specifically on the README, I put a suggestion to include the modules list of CharlesCD because I considered that, if someone is reading about the project for the first time, it'd be interesting to give this quick context. Let me know if it makes sense. :)

IT does, I liked the idea!

2021-12-10 14:06 UTC, mdcpmoreira reviewed
Review done, @jessica-tw :)

2021-12-10 14:13 UTC, mdcpmoreira approved these changes

2021-12-10 14:14 UTC, barbararochazup approved these changes

2021-12-10 14:14 UTC, merged