Fix vs logs
ZupIT/charlescd pull request #1419
Opened 2021-09-16 20:07 UTC by thallesfreitaszup

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

## Results

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

### Request (if appropriate):
> Url: **POST** {{url}}/hello/{{hello-code}}

Payload:
```json
{
    "key" : "value"
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "key" :  "value"
}
```
### Screenshots (if appropriate):

2021-09-20 16:14 UTC, barbararochazup requested changes
Update headers with 2021 year

2021-09-21 13:10 UTC, tiagoangelozup reviewed
Just a few suggestions

2021-09-21 13:10 UTC, tiagoangelozup commented on butler/src/app/v2/operator/logs-aggregator/kubernetes-events-aggregator.ts
> +      await this.checkResourceAnnotation(resource, event)
Maybe a wrapper of KubernetesObject could improve the code readability. 
e.g.
```ts
class ResourceWrapper {
  private readonly _resource: KubernetesObject
  private readonly _spec?: Record<string, unknown>

  constructor(resource: KubernetesObject) {
    this._resource = resource
    if (resource.kind === AppConstants.CHARLES_CUSTOM_RESOURCE_ROUTES_KIND) {
      this._spec = plainToClass(K8sManifestWithSpec, this).spec
    }
  }

  public get circles(): CharlesCircle[] {
    return this._spec ? this._spec.circles as CharlesCircle[] : []
  }

  public get deploymentId(): string | undefined {
    const deploymentId = this._resource.metadata?.labels?.[AppConstants.DEPLOYMENT_ID_LABEL]
    if (deploymentId) return deploymentId
    return this._spec ? this._spec.deploymentId as string : undefined
  }
}
```

2021-09-21 13:10 UTC, tiagoangelozup commented on butler/src/app/v2/operator/logs-aggregator/kubernetes-events-aggregator.ts
> +          deploymentId => this.saveLogs(deploymentId, log)
I think the `LogRepository` is able to persist multiple entities at once with a single transaction.

2021-09-27 17:44 UTC, barbararochazup approved these changes

2021-09-28 12:38 UTC, tiagoangelozup approved these changes

2021-11-08 17:21 UTC, merged