Create metrics groups
ZupIT/charlescd pull request #418
Opened 2020-08-21 20:54 UTC by bCatanant

Create a new layer and new segment in the circles screen.

2020-09-01 13:16 UTC, celiofilhozup submitted a review, later dismissed
LGTM

2020-09-08 14:31 UTC, emiteze requested changes

2020-09-08 14:31 UTC, emiteze commented on moove/metrics/src/main/kotlin/io/charlescd/moove/metrics/connector/compass/CompassApi.kt
> +    ): List<CompassDatasourceResponse>
Acho que o nome desse parametro devera chamar "healthy", não? Outro ponto é que esse endpoint se eu passar false ele me traz os datasources !healthy certo? Então acho que o nome da função na api deveria ser findDatasource.

2020-09-08 14:31 UTC, emiteze commented on moove/metrics/src/main/kotlin/io/charlescd/moove/metrics/connector/compass/CompassCreateDatasourceRequest.kt
> +    val health: Boolean,
Msm coisa aqui pra esse cenário, se a property é boolean, então acho que o parametro deveria chamar healthy

2020-09-08 14:31 UTC, emiteze commented on moove/metrics/src/main/kotlin/io/charlescd/moove/metrics/connector/compass/CompassDatasourceResponse.kt
> +    val health: Boolean,
Msm coisa aqui pra esse cenário, se a property é boolean, então acho que o parametro deveria chamar healthy

2020-09-09 19:54 UTC, cpgo commented on compass/internal/tests/dispatcher_test.go
> +	s.DB.Exec("DELETE FROM metric_filters")
We should pay atention when using `delete` for cleanup as it only deletes data. Sequences, unused indexes and so on are left on the table.
This maybe could be a source of bugs in the future, one alternative is to use `truncate cascade` instead of `delete`

2020-09-09 19:54 UTC, cpgo approved these changes

2020-09-09 19:56 UTC, emiteze approved these changes

2020-09-10 12:02 UTC, merged