Update react hook form
ZupIT/charlescd pull request #464
Opened 2020-09-04 18:56 UTC by washingtonsoares

Update React Hook Form version from 5.6.2 to 6.7.0

2020-09-04 19:36 UTC, ifdouglas requested changes

2020-09-04 19:36 UTC, ifdouglas commented on ui/src/core/utils/validation.ts
> +  forEach(fields, (value: string | Module[]) => {
Acho que esse arquivo deveria ser genérico e não ser tipado com algo tão específico.

2020-09-08 12:15 UTC, washingtonsoares commented on ui/src/core/utils/validation.ts
> +  forEach(fields, (value: string | Module[]) => {
Indeed

2020-09-22 17:22 UTC, ifdouglas submitted a review, later dismissed

2020-10-07 20:02 UTC, luanecavalcantizup commented on ui/src/core/components/Form/Select/MultiCheck/index.tsx
> +  control: Control<any>;
can type any be change to another type?

2020-10-19 13:38 UTC, closed without merging