Create priority circles
ZupIT/charlescd pull request #469
Opened 2020-09-09 13:20 UTC by thallesfreitaszup

2020-09-23 19:21 UTC, emiteze requested changes

2020-09-23 19:21 UTC, emiteze commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    private LocalDateTime createdAt;
Nao rola usar a property do spring que padroniza serialização de localdatetime no jackson? Se nao me engano a property é spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS

2020-09-23 19:21 UTC, emiteze commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/Segmentation.java
> +    private LocalDateTime createdAt;
Nao rola usar a property do spring que padroniza serialização de localdatetime no jackson? Se nao me engano a property é spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS

2020-09-23 19:21 UTC, emiteze commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/service/IdentificationService.java
> +    LinkedHashSet<Circle> identify(IdentificationRequest request);
Sò uma duvida, pq não mantemos o Set aqui ja que ele é a collection mais genérica? Ai na hora de montar o response poderiamos montar com LinkedHashSet normal

2020-09-23 19:21 UTC, emiteze commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/service/impl/IdentificationServiceImpl.java
> +    public LinkedHashSet<Circle> identify(IdentificationRequest request) {
Sò uma duvida, pq não mantemos o Set aqui ja que ele é a collection mais genérica? Ai na hora de montar o response poderiamos montar com LinkedHashSet normal

2020-09-23 19:21 UTC, emiteze commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/service/client/request/CircleMatcherRequest.kt
> +    val createdAt: LocalDateTime? = null
Nesse cenário pelo que entendi o PR traz circulos em prioridade por ordem de criação, certo? Só que o moove vai sempre enviar null pro circle matcher, então todos vão ser priorizados da mesma forma.

2020-09-23 19:24 UTC, lucasbfernandes requested changes

2020-09-23 19:24 UTC, lucasbfernandes commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/request/SegmentationRequest.java
> +        return new Segmentation(this.name, this.node, this.reference, this.circleId, this.type,
Indent this correctly

2020-09-25 19:25 UTC, thallesfreitaszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/service/client/request/CircleMatcherRequest.kt
> +    val createdAt: LocalDateTime? = null
Corrigido

2020-09-25 19:25 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/service/impl/IdentificationServiceImpl.java
> +    public LinkedHashSet<Circle> identify(IdentificationRequest request) {
Corrigido

2020-09-25 19:25 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/service/IdentificationService.java
> +    LinkedHashSet<Circle> identify(IdentificationRequest request);
Corrigido

2020-09-25 19:25 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/Segmentation.java
> +    private LocalDateTime createdAt;
Corrigido

2020-09-25 19:25 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    private LocalDateTime createdAt;
Corrigido

2020-09-25 19:25 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/response/IdentificationResponse.java
> +    private LinkedHashSet<CircleResponse> circles;
Corrigido

2020-09-25 19:27 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/request/SegmentationRequest.java
> +        return new Segmentation(this.name, this.node, this.reference, this.circleId, this.type,
corrigido

2020-09-28 15:12 UTC, emiteze approved these changes

2020-09-28 15:12 UTC, emiteze commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/service/IdentificationService.java
> +import java.util.LinkedHashSet;
Esse import nao está sendo utilizado

2020-09-29 14:49 UTC, emiteze approved these changes

2020-09-30 18:52 UTC, lucasbfernandes approved these changes

2020-10-15 14:53 UTC, merged