Identify only active circles
ZupIT/charlescd pull request #489
Opened 2020-09-15 14:31 UTC by thallesfreitaszup

2020-09-23 19:47 UTC, emiteze requested changes

2020-09-23 19:47 UTC, emiteze commented on moove/application/pom.xml
> +        </dependency>
Pq essa dependencia do infra foi adicionada no application? Fere um pouco o conceito de dependency rule do clean arch, ja que nesse caso a camada de use case nao deveria conhecer nada além do domain

2020-09-23 19:47 UTC, emiteze commented on moove/domain/src/main/kotlin/io/charlescd/moove/domain/service/CircleMatcherService.kt
> +    fun update(circle: Circle, previousReference: String, matcherUri: String, status: Boolean)
Nao seria melhor usar o mesmo atributo do updateImport? Talvez active faz mais sentido

2020-09-25 18:11 UTC, thallesfreitaszup commented on moove/application/pom.xml
> +        </dependency>
No teste do callback de deployment agora tem a dependencia do client do circle matcher e ai é necessário esse import para encontrar a classe do client

2020-09-30 11:59 UTC, emiteze commented on moove/application/pom.xml
> +        </dependency>
Acho que o certo nesse cenário é vc nao mockar o client feign, e sim a interface CircleMatcherService que é do domain, dessa forma vc nao precisa mockar as chamadas do feign e nao precisa incluir esse import do infra no application, mesmo que com scope de test

2020-09-30 12:02 UTC, emiteze requested changes

2020-09-30 12:02 UTC, emiteze commented on moove/application/src/test/groovy/io/charlescd/moove/application/deployment/impl/DeploymentCallbackInteractorImplTest.groovy
> +        1 * circleMatcherClient.update(_, _, _)
Aqui vc deveria mockar o CircleMatcherService e nao o client. O mock do client fica na classe do CircleMatcherClientServiceTest. Depois da uma olhada no CreateBuildInteractorImplTest pra vc ter uma noção

2020-09-30 16:27 UTC, thallesfreitaszup commented on moove/application/pom.xml
> +        </dependency>
Corrigido!

2020-09-30 16:27 UTC, thallesfreitaszup commented on moove/application/src/test/groovy/io/charlescd/moove/application/deployment/impl/DeploymentCallbackInteractorImplTest.groovy
> +        1 * circleMatcherClient.update(_, _, _)
corrigido

2020-09-30 17:55 UTC, emiteze submitted a review, later dismissed

2020-09-30 18:51 UTC, lucasbfernandes requested changes

2020-09-30 18:51 UTC, lucasbfernandes commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/request/SegmentationRequest.java
> +                isDefault, active);
Fix indentation

2020-10-02 20:07 UTC, lucasbfernandes approved these changes

2020-10-13 18:29 UTC, emiteze submitted a review, later dismissed

2020-10-19 18:26 UTC, closed without merging