Adding openresty oidc
ZupIT/charlescd pull request #505
Opened 2020-09-17 21:58 UTC by monicaribeiro

2020-09-18 13:40 UTC, lucassaleszup requested changes

2020-09-18 13:40 UTC, lucassaleszup commented on install/helm-chart/charts/nginx/templates/nginx-conf.yaml
> -            {{ if .Values.circlematcher.enabled}}
you can keep the circle matcher endpoint.

2020-09-18 13:40 UTC, lucassaleszup commented on install/helm-chart/charts/nginx/templates/nginx.deployment.yaml
> +          image: monicaribeiro/openresty:alpinefat-openidc
Add this image on ZupCharles repository. (Célio/Ricardo)

2020-09-18 13:40 UTC, lucassaleszup commented on install/helm-chart/values.yaml
> +  circleId: example
This property is not required and you can remove it.

2020-09-18 14:26 UTC, celiofilhozup commented on install/helm-chart/charts/nginx/templates/nginx.deployment.yaml
> +          image: monicaribeiro/openresty:alpinefat-openidc
@ricardorames eu ainda nao tenho acesso ao dockerhub, consegue criar la pra galera fazer o push?

2020-09-18 14:31 UTC, monicaribeiro commented on install/helm-chart/charts/nginx/templates/nginx-conf.yaml
> -            {{ if .Values.circlematcher.enabled}}
Done!

2020-09-18 14:33 UTC, monicaribeiro commented on install/helm-chart/values.yaml
> +  circleId: example
Done!

2020-09-24 20:23 UTC, celiofilhozup requested changes

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/values.yaml
> +    name: realwavelab.azurecr.io/charlescd-ui:release-darwin-front-livepass-rc-7
voltar para docker hub

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/values.yaml
> +    name: realwavelab.azurecr.io/charlescd-moove:release-darwin-devcraft-v-4
voltar para docker hub

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/values.yaml
> +    endpoint: https://idm-dev.continuousplatform.com/auth/realms/ZupDev/.well-known/openid-configuration
esse valor nao deveria estar aqui

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/templates/charlescd-moove-deployment.yaml
> +              value: "ZupDev"
esse valor nao deveria ser esse

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/templates/charlescd-ui-deployment.yaml
> +              value: ZupDev
esse valor nao deveria ser esse

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/values.yaml
> +  keycloakHost: "https://idm-dev.continuousplatform.com/auth"
esse valor nao deveria ser esse

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/values.yaml
> +  authUri: https://idm-dev.continuousplatform.com
esse valor nao deveria ser esse

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/templates/charlescd-moove-deployment.yaml
> +              value: "718462e0-e3ba-4e7e-90e3-8bf78cca7dbf"
esse valor nao deveria ser esse

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/templates/charlescd-moove-deployment.yaml
> +              value: "charlescd-client"
conferir se com a nossa instalação o valor correto é esse mesmo

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/charts/octopipe-charlescd/templates/cluster-role.yaml
> +#   - watch
Voltar isso

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/charts/octopipe-charlescd/templates/cluster-role-binding.yaml
> +#   namespace: {{ .Release.Namespace }}
Voltar isso

2020-09-24 20:23 UTC, celiofilhozup commented on install/helm-chart/charts/nginx/values.yaml
> +  endpoint: example
esse example poderia ser mostrando o padrao do formato da url openid

2020-09-25 21:12 UTC, closed without merging