Feature change login process
ZupIT/charlescd pull request #506
Opened 2020-09-18 14:07 UTC by eduardomiyoshizup

2020-09-18 14:16 UTC, emiteze requested changes

2020-09-18 14:16 UTC, emiteze commented on moove/api/src/main/kotlin/io/charlescd/moove/api/MooveExceptionHandler.kt
> +    @ExceptionHandler(UnauthorizedException::class)
Maybe we should change from UnauthorizedException to ForbiddenException, cause unauthorized reminds of 401, which is not correct for our situation.

2020-09-18 14:16 UTC, emiteze commented on moove/domain/src/main/kotlin/io/charlescd/moove/domain/MooveErrorCode.kt
> +    NOT_AUTHORIZED("not.authorized")
Also we should change this error code to FORBIDDEN instead

2020-09-18 14:16 UTC, emiteze commented on moove/domain/src/main/kotlin/io/charlescd/moove/domain/exceptions/UnauthorizedException.kt
> +class UnauthorizedException : RuntimeException("Access denied!")
Maybe we should change from UnauthorizedException to ForbiddenException, cause unauthorized reminds of 401, which is not correct for our situation.

2020-09-18 14:16 UTC, emiteze commented on moove/web/src/main/resources/locale/messages.properties
> +not.authorized=Not Authorized
Also change this message to a forbidden message

2020-09-18 14:16 UTC, emiteze commented on moove/web/src/main/resources/locale/messages_pt_BR.properties
> +not.authorized=Sem autorização
Also change this message to a forbidden message

2020-09-21 14:21 UTC, emiteze requested changes

2020-09-21 14:21 UTC, emiteze commented on moove/domain/src/main/kotlin/io/charlescd/moove/domain/MooveErrorCode.kt
> +    forbidden("forbidden")
Put this ErrorCode in upper case

2020-09-21 14:21 UTC, emiteze commented on moove/web/src/main/resources/locale/messages_pt_BR.properties
> +forbidden=Forbidden
Translate this message to portuguese

2020-09-21 21:46 UTC, emiteze approved these changes

2020-09-22 20:45 UTC, emiteze submitted a review, later dismissed

2020-09-22 22:31 UTC, pedroborgeszup approved these changes

2020-09-23 15:33 UTC, ifdouglas approved these changes

2020-09-23 15:34 UTC, emiteze approved these changes

2020-09-23 15:34 UTC, merged