Fix users group
ZupIT/charlescd pull request #519
Opened 2020-09-23 19:04 UTC by Leandroqo

2020-09-24 17:55 UTC, bCatanant commented on ui/src/modules/Settings/Credentials/Sections/UserGroup/__tests__/FormUserGroup.spec.tsx
> +test('should find a user group by name', async () => {
Remove coments on mockResponseOnce's

2020-09-24 18:01 UTC, luanecavalcantizup commented on ui/src/modules/Settings/Credentials/Sections/UserGroup/__tests__/FormUserGroup.spec.tsx
> +test('should find a user group by name', async () => {
vdd, obrigado :)

2020-09-24 18:02 UTC, bCatanant approved these changes

2020-09-24 18:26 UTC, bCatanant approved these changes

2020-09-28 17:30 UTC, ifdouglas requested changes
### Maybe a behavior issue
- After selecting an UserGroup and then try change to another, I can not delete the filter unless I start typing.

2020-09-28 17:30 UTC, ifdouglas commented on ui/src/modules/Settings/Credentials/Sections/UserGroup/Form.tsx
> +import debounce from 'debounce-promise';
`lodash/debounce` does not attend?

2020-09-28 18:10 UTC, ifdouglas approved these changes

2020-09-30 17:26 UTC, merged