Chnage history to force redirect
ZupIT/charlescd pull request #548
Opened 2020-09-30 18:55 UTC by ifdouglas

Closes #411

2020-09-30 19:12 UTC, bCatanant submitted a review, later dismissed

2020-10-02 18:55 UTC, bCatanant approved these changes

2020-10-02 18:56 UTC, Leandroqo requested changes

2020-10-02 18:56 UTC, Leandroqo commented on ui/src/modules/Auth/Login/__tests__/Login.spec.tsx
> +  await wait();
if we do something like this:
```suggestion
  await waitFor(() => expect(window.location.href).toEqual(routes.workspaces));
```
it works?

2020-10-02 19:07 UTC, washingtonsoares requested changes

2020-10-02 19:07 UTC, washingtonsoares commented on ui/src/modules/Auth/Login/__tests__/Login.spec.tsx
> +  const iconCharles = screen.queryByTestId('icon-charles-logo');
Como conversamos ontem no Chapter, só faz sentido usar o `queryBy*` se estiver fazendo uma asserção para verificar se um elemento **não** está presente na página (https://testing-library.com/docs/dom-testing-library/api-queries#queryby).

Pro restante dos casos, é mais conciso usar o `getBy*` ou `findBy*` mesmo

2020-10-02 19:07 UTC, washingtonsoares commented on ui/src/modules/Auth/Login/__tests__/Login.spec.tsx
> +  await wait();
I don't think so. Cause of that we need to update Testing Library ASAP

2020-10-02 19:14 UTC, Leandroqo submitted a review, later dismissed

2020-10-02 19:21 UTC, washingtonsoares approved these changes

2020-10-02 19:22 UTC, bCatanant approved these changes

2020-10-02 19:24 UTC, Leandroqo approved these changes

2020-10-16 13:40 UTC, merged