add ends with option
ZupIT/charlescd pull request #549
Opened 2020-10-01 17:47 UTC by leandrorodrigueszup

Signed-off-by: LucasSales <lucas.sales@zup.com.br>

2020-10-07 18:27 UTC, thallesfreitaszup requested changes

2020-10-07 18:27 UTC, thallesfreitaszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/circle/request/CreateCircleRequest.kt
> +        ENDS_WITH,
Missing MATCHES expression here

2020-10-07 18:27 UTC, thallesfreitaszup commented on ui/src/modules/Circles/Segments/conditional.options.tsx
> +  { value: 'NOT_EQUAL', label: 'Not equal' },
Missing MATCHES expression here

2020-10-07 18:56 UTC, leandrorodrigueszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/circle/request/CreateCircleRequest.kt
> +        ENDS_WITH,
Done

2020-10-07 18:56 UTC, leandrorodrigueszup commented on ui/src/modules/Circles/Segments/conditional.options.tsx
> +  { value: 'NOT_EQUAL', label: 'Not equal' },
Done

2020-10-07 19:19 UTC, thallesfreitaszup approved these changes

2020-10-08 14:02 UTC, lucasbfernandes requested changes

2020-10-08 14:02 UTC, lucasbfernandes commented on circle-matcher/src/main/java/io/charlescd/circlematcher/infrastructure/Constants.java
> +    public static final String NOT_EQUALS_EXPRESSION = "%s.indexOf(%s) == -1";
Why not compare strings using the JS inequality operator?

%s !== %s

2020-10-08 14:08 UTC, lucasbfernandes approved these changes

2020-11-04 14:46 UTC, closed without merging

2020-11-04 14:47 UTC, eliasalveszup commented
Canceled due to another PR #649