Metric actions v 2
ZupIT/charlescd pull request #609
Opened 2020-10-19 17:51 UTC by bCatanant

Add new actions tab to metrics group view.

2020-10-21 13:44 UTC, ifdouglas requested changes

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(dropdown);
```suggestion
  userEvent.click(dropdown);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(screen.getByText('Edit action'));
```suggestion
  userEvent.click(screen.getByText('Edit action'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(dropdown);
```suggestion
  userEvent.click(dropdown);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(screen.getByText('Delete action'));
```suggestion
  userEvent.click(screen.getByText('Delete action'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(dropdown);
```suggestion
  userEvent.click(dropdown);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(screen.getByText('Delete action'));
```suggestion
  userEvent.click(screen.getByText('Delete action'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(screen.getByText('Yes, delete'));
```suggestion
  userEvent.click(screen.getByText('Yes, delete'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(dropdown);
```suggestion
  userEvent.click(dropdown);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(screen.getByText('Delete action'));
```suggestion
  userEvent.click(screen.getByText('Delete action'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(screen.getByText('No'));
```suggestion
  userEvent.click(screen.getByText('No'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/index.tsx
> +              id={'add-metric'}
```suggestion
              id="add-metric"
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/index.tsx
> +              id={'add-action'}
```suggestion
              id="add-action"
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  const metricsGroupMenu = screen.getByTestId('icon-vertical-dots');
```suggestion
  const metricsGroupMenu = await waitForElement(() => screen.queryByTestId('icon-vertical-dots'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(metricsGroupMenu);
```suggestion
  userEvent.click(metricsGroupMenu);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(screen.getByText('Edit'));
```suggestion
  userEvent.click(screen.getByText('Edit'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(submit);
```suggestion
  userEvent.click(submit);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(addMetric);
```suggestion
  userEvent.click(addMetric);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(actionTab);
```suggestion
  userEvent.click(actionTab);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(actionTab);
```suggestion
  userEvent.click(actionTab);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(metricDropdown[1]);
```suggestion
  userEvent.click(metricDropdown[1]);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(screen.getByText('Edit action'));
```suggestion
  userEvent.click(screen.getByText('Edit action'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(goBack);
```suggestion
  userEvent.click(goBack);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(metricDropdown[1]);
```suggestion
  userEvent.click(metricDropdown[1]);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(screen.getByText('Delete action'));
```suggestion
  userEvent.click(screen.getByText('Delete action'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(actionTab);
```suggestion
  userEvent.click(actionTab);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(metricDropdown[1]);
```suggestion
  userEvent.click(metricDropdown[1]);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(screen.getByText('Edit metric'));
```suggestion
  userEvent.click(screen.getByText('Edit metric'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(metricDropdown[1]);
```suggestion
  userEvent.click(metricDropdown[1]);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(screen.getByText('Delete'));
```suggestion
  userEvent.click(screen.getByText('Delete'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  fireEvent.click(addAction);
```suggestion
  userEvent.click(addAction);
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  const addMetric = screen.getByTestId('button-default-add-metric');
```suggestion
  const addMetric = await waitForElement(() => screen.queryByTestId('button-default-add-metric'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  const actionTab = screen.getByTestId('tab-1');
```suggestion
  const actionTab = await waitForElement(() => screen.getByTestId('tab-1'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  const metricDropdown = screen.getAllByTestId('icon-vertical-dots');
```suggestion
  const metricDropdown = await waitForElement(() => screen.getAllByTestId('icon-vertical-dots'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  const metricDropdown = screen.getAllByTestId('icon-vertical-dots');
```suggestion
  const metricDropdown = await waitForElement(() => screen.getAllByTestId('icon-vertical-dots'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  const actionTab = screen.getByTestId('tab-1');
```suggestion
  const actionTab = await waitForElement(() => screen.getByTestId(tab-1'));
```

2020-10-21 13:44 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/__tests__/MetricsGroups.spec.tsx
> +  const actionTab = screen.getByTestId('tab-1');
```suggestion
  const actionTab = await waitForElement(() => screen.getByTestId(tab-1'));
```

2020-10-22 19:19 UTC, ifdouglas requested changes

2020-10-22 19:19 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +import { render, screen, fireEvent, wait } from 'unit-test/testUtils';
`wait` is not been used here

2020-10-22 19:19 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(dropdown);
```suggestion
  userEvent.click(dropdown);
```

2020-10-22 19:19 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(screen.getByText('Edit action'));
```suggestion
  userEvent.click(screen.getByText('Edit action'));
```

2020-10-22 20:03 UTC, washingtonsoares commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(dropdown);
It only works with `fireEvent`

2020-10-22 20:04 UTC, washingtonsoares commented on ui/src/modules/Circles/Comparation/Item/MetricsGroups/MetricsGroupCard/__tests__/ActionCard.spec.tsx
> +  fireEvent.click(screen.getByText('Edit action'));
It only works with `fireEvent`

2020-10-22 20:06 UTC, ifdouglas approved these changes

2020-11-04 20:15 UTC, washingtonsoares approved these changes

2020-11-04 20:27 UTC, ifdouglas approved these changes

2020-11-04 20:30 UTC, merged