Identify only active circles
ZupIT/charlescd pull request #611
Opened 2020-10-19 18:28 UTC by thallesfreitaszup

Fixes https://github.com/ZupIT/charlescd/issues/440
Signed-off-by: Thalles Freitas <thalles.freitas@zup.com.br>

2020-11-06 14:06 UTC, lucasbfernandes requested changes

2020-11-06 16:47 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/Segmentation.java
> +    }
i agree

2021-02-08 19:55 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/request/SegmentationRequest.java
> +            this.name, this.node, this.reference, this.circleId, this.type, workspaceId, isDefault, active,
Why the lack of `this` in just some attributes? Since none of them are static

2021-02-08 19:56 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/configuration/ApplicationReadyListener.java
> +public class ApplicationReadyListener implements ApplicationListener<ApplicationReadyEvent> {
A more intuitive class name would be better

2021-02-08 19:57 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/configuration/ApplicationReadyListener.java
> +            this.keyMetadataRepository.remove(keyMetadata);
Is necessary to remove and create again?? There's no way to simply update?

2021-02-08 20:02 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/request/SegmentationRequest.java
> +    public Boolean getActive() {
The correct convention for boolean getter is `isActive`

2021-02-08 20:03 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    public Boolean getActive() {
The correct convention for boolean getter is `isActive`

2021-02-08 20:14 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/configuration/ApplicationReadyListener.java
> +            this.keyMetadataRepository.remove(keyMetadata);
Yes. We do the same in the update endpoint https://stackoverflow.com/questions/32927213/efficient-way-redis-set-member-update

2021-02-08 20:29 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/request/SegmentationRequest.java
> +            this.name, this.node, this.reference, this.circleId, this.type, workspaceId, isDefault, active,
done

2021-02-08 20:30 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    public Boolean getActive() {
done

2021-02-08 20:30 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/request/SegmentationRequest.java
> +    public Boolean getActive() {
done

2021-02-08 20:30 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/configuration/ApplicationReadyListener.java
> +public class ApplicationReadyListener implements ApplicationListener<ApplicationReadyEvent> {
suggestions?

2021-02-09 13:21 UTC, lucasbfernandes requested changes

2021-02-09 13:21 UTC, lucasbfernandes commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/configuration/ApplicationReadyListener.java
> +package io.charlescd.circlematcher.api.configuration;
Insert license header

2021-02-09 13:21 UTC, lucasbfernandes commented on circle-matcher/src/test/groovy/io/charlescd/circlematcher/configuration/ApplicationReadyEventTest.groovy
> +package io.charlescd.circlematcher.configuration
Insert license header

2021-02-09 13:29 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/configuration/ApplicationReadyListener.java
> +package io.charlescd.circlematcher.api.configuration;
done

2021-02-09 13:29 UTC, thallesfreitaszup commented on circle-matcher/src/test/groovy/io/charlescd/circlematcher/configuration/ApplicationReadyEventTest.groovy
> +package io.charlescd.circlematcher.configuration
done

2021-02-09 14:12 UTC, eliasalveszup approved these changes

2021-02-09 14:19 UTC, lucasbfernandes submitted a review, later dismissed

2021-02-17 17:07 UTC, lucasbfernandes approved these changes

2021-02-17 20:44 UTC, eliasalveszup approved these changes

2021-02-19 16:13 UTC, merged

2021-05-17 18:23 UTC, ricardorames commented
Fixed on release [0.5.7](https://github.com/ZupIT/charlescd/releases/tag/0.5.7).