Dynamic id default
ZupIT/charlescd pull request #622
Opened 2020-10-20 18:26 UTC by thallesfreitaszup

2020-11-03 18:16 UTC, cpgo requested changes

2020-11-03 18:16 UTC, cpgo commented on butler/src/resources/migrations/20200917141900-add-default-field-to-deployment.ts
> +  public async up(queryRunner: QueryRunner) : Promise<void> {
Since we have the `DEFAULT_CIRCLE_ID` constant we could set it as default on a migration and make `the circle_id` not nullable.

2020-11-03 19:21 UTC, lucasbfernandes requested changes

2020-11-03 19:21 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/istio-deployment-manifests.utils.ts
> +      if (activeCircleId && activeCircleId !== circleId && !component?.deployment?.defaultCircle) {
Maybe improve this? 

```!component?.deployment?.defaultCircle```

If either component or deployment are undefined/null, it will push a new subset to the destination rules object

2020-11-03 19:21 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/istio-deployment-manifests.utils.ts
> +      if (activeCircleId && activeCircleId !== circleId && !component?.deployment?.defaultCircle) {
I think we must ensure that component and deployment are valid objects before checking if they represent a circle deployment. What do you think? @cpgo @thallesfreitaszup

2020-11-03 19:21 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/istio-deployment-manifests.utils.ts
> +      if (activeCircleId && activeCircleId !== circleId && !component?.deployment?.defaultCircle) {
Maybe improve this?

```!component?.deployment?.defaultCircle```

If either component or deployment are undefined/null, it will push a new subset to the virtual services object

2020-11-03 19:21 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/istio-deployment-manifests.utils.ts
> +      if (component.deployment && !component.deployment?.defaultCircle) {
Maybe improve this?

```!component?.deployment?.defaultCircle```

If either component or deployment are undefined/null, it will push a new subset to the virtual services object

2020-11-03 19:21 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/istio-deployment-manifests.utils.ts
> +      if (activeCircleId && activeCircleId !== circleId && !component?.deployment?.defaultCircle) {
This verification is repeated across several places in the code base. What do you think about extracting it to a utilitary (utils) method?

2020-11-03 19:21 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/istio-undeployment-manifests.utils.ts
> +      if (activeCircleId &&  !component.deployment?.defaultCircle && circleId !== component.deployment?.circleId) {
If deployment is undefined/null then this component will be interpreted as a non default circle, which might be incorrect.

Improve this ```!component.deployment?.defaultCircle```

2020-11-03 19:21 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/istio-undeployment-manifests.utils.ts
> +      if (activeCircleId && activeCircleId !== circleId && !component.deployment?.defaultCircle) {
Improve this ```!component.deployment?.defaultCircle```

2020-11-03 19:21 UTC, lucasbfernandes commented on butler/src/resources/migrations/20200917141900-add-default-field-to-deployment.ts
> +      name: 'default',
I would change this. 'default' does not mean anything

2020-11-03 19:21 UTC, lucasbfernandes commented on butler/src/resources/migrations/20200917141900-add-default-field-to-deployment.ts
> +      name: 'default',
Maybe to_default_circle? It has more semantic

What do you think @cpgo ?

2020-11-03 19:27 UTC, lucasbfernandes commented on butler/src/resources/migrations/20200917141900-add-default-field-to-deployment.ts
> +      name: 'default',
Or maybe is_default

2020-11-03 19:31 UTC, cpgo commented on butler/src/app/v2/core/integrations/utils/istio-deployment-manifests.utils.ts
> +      if (activeCircleId && activeCircleId !== circleId && !component?.deployment?.defaultCircle) {
Regarding the safe access to deployment, since this is a required relation on the database we should simply make sure the query returns a component with a deployment earlier in the program.

> I think we must ensure that component and deployment are valid objects before checking if they represent a circle deployment. What do you think? @cpgo @thallesfreitaszup

What do you mean by valid objects? If the component object has a deployment?

2020-11-03 19:40 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/istio-deployment-manifests.utils.ts
> +      if (activeCircleId && activeCircleId !== circleId && !component?.deployment?.defaultCircle) {
> What do you mean by valid objects? If the component object has a deployment?

yes

> Regarding the safe access to deployment, since this is a required relation on the database we should simply make sure the query returns a component with a deployment earlier in the program.

I agree. We should improve our queries. The only problem I see is that we can't make the components attribute non-optional for the deployment interface, since we use it without components inside the Execution entity.

2020-11-03 19:54 UTC, cpgo commented on butler/src/resources/migrations/20200917141900-add-default-field-to-deployment.ts
> +      name: 'default',
> Maybe to_default_circle? It has more semantic
> 
> What do you think @cpgo ?
`is_default_circle` maybe

2020-11-04 19:09 UTC, lucasbfernandes requested changes

2020-11-04 19:09 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/deployment.utils.ts
> +  },
Remove this

2020-11-04 19:09 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/istio-deployment-manifests.utils.ts
> +      if (component.deployment && !DeploymentUtils.getIsDefault(component)) {
```if (component.deployment && component.deployment.defaultCircle)```

2020-11-05 13:39 UTC, cpgo approved these changes

2020-11-05 14:32 UTC, lucasbfernandes submitted a review, later dismissed

2020-11-12 19:05 UTC, lucasbfernandes approved these changes

2020-11-12 19:07 UTC, cpgo approved these changes

2020-11-12 19:10 UTC, merged