Test registry connectivity gcr
ZupIT/charlescd pull request #627
Opened 2020-10-21 11:27 UTC by barbararochazup

Test if registry config GCR type is a valid config

Backend Postman Tests:
![postman_testes_gcr](https://user-images.githubusercontent.com/68229507/96713552-2a800100-1377-11eb-907c-4d1cba2c9827.png)

2020-11-03 14:43 UTC, monicaribeiro requested changes

2020-11-03 15:23 UTC, barbararochazup commented on villager/src/main/java/io/charlescd/villager/api/resources/registry/DockerRegistryResource.java
> +    @Path("/config-validation")
Realizado a alteração sugerida

2020-11-03 17:40 UTC, Leandroqo requested changes

2020-11-03 17:40 UTC, Leandroqo commented on ui/src/core/providers/base/hooks.ts
> +        console.log('error', error);
what do you think in remove the log error?

2020-11-03 18:40 UTC, luanecavalcantizup commented on ui/src/core/providers/base/hooks.ts
> +        console.log('error', error);
removed the log, thanks 👍

2020-11-13 13:21 UTC, monicaribeiro approved these changes

2020-11-13 14:34 UTC, Leandroqo submitted a review, later dismissed

2020-12-01 18:00 UTC, monicaribeiro approved these changes

2020-12-03 13:37 UTC, Leandroqo approved these changes

2020-12-08 20:12 UTC, monicaribeiro requested changes

2020-12-08 20:12 UTC, monicaribeiro commented on moove/web/src/main/resources/locale/messages_pt_BR.properties
> +villager.unexpected.error=Um erro inesperado ocorreu e nós estamos trabalhando para resolver ele.
Suggestion: do not add this part ` nós estamos trabalhando para resolver ele. `, because it could be an unknown error.

2020-12-08 20:19 UTC, monicaribeiro commented on moove/web/src/main/resources/locale/messages_pt_BR.properties
> +villager.unexpected.error=Um erro inesperado ocorreu e nós estamos trabalhando para resolver ele.
( and we would miss the community feedback)

2020-12-09 21:36 UTC, barbararochazup commented on moove/web/src/main/resources/locale/messages_pt_BR.properties
> +villager.unexpected.error=Um erro inesperado ocorreu e nós estamos trabalhando para resolver ele.
I didn't thinking this, thanks. I did the change suggestion

2020-12-10 17:10 UTC, merged