Harbor integration
ZupIT/charlescd pull request #628
Opened 2020-10-21 13:26 UTC by icaroafonsozup

Created integration with [Harbor  Registry](https://goharbor.io/).

Connection data needed: host, username and password.

![Screen Shot 2020-10-19 at 14 01 59](https://user-images.githubusercontent.com/8366062/96487932-a9f4bf80-1213-11eb-9e86-7ab64e995a84.png)

![Screen Shot 2020-10-19 at 14 02 33](https://user-images.githubusercontent.com/8366062/96487992-bda02600-1213-11eb-9149-d99d654ec12e.png)

2020-10-26 13:40 UTC, ifdouglas requested changes

2020-10-26 13:40 UTC, ifdouglas commented on ui/src/modules/Settings/Credentials/__tests__/FormRegistry.spec.tsx
> +  fireEvent.click(radioAuthButton)
```suggestion
  userEvent.click(radioAuthButton)
```

2020-10-27 19:22 UTC, ifdouglas submitted a review, later dismissed

2020-11-17 17:47 UTC, emiteze approved these changes

2020-11-17 19:58 UTC, ifdouglas approved these changes

2020-11-17 20:21 UTC, merged