Git not required hypothesis board
ZupIT/charlescd pull request #630
Opened 2020-10-22 13:22 UTC by icaroafonsozup

Deleted the git Configuration validation from checkCurrentWorkspaceStatus method, called when we tried to save a Workspace config.

Created treatment when tried to find and create modules, without Git configurations in settings.

Signed-off-by: Icaro Gabriel Marques Afonso <icaro.afonso@zup.com.br>

2020-11-06 19:53 UTC, arthurpuccizup approved these changes

2020-11-06 20:42 UTC, emiteze requested changes

2020-11-06 20:42 UTC, emiteze commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/mapper/GitConfigurationMapper.kt
> +        return if (!resultSet.wasNull()) {
Mano, nao conheço muito o resultSet (jpa <3) mas uma duvida. Pelo que eu li, esse wasNull() checa se o registro anterior do resultSet tava null, e nao é esse o cenário pra fazer o deserializar do banco, pq o gitconfiguration nesse cenário tá na linha atual do resultSet (me corrija se eu estiver errado)

2020-11-06 21:04 UTC, icaroafonsozup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/mapper/GitConfigurationMapper.kt
> +        return if (!resultSet.wasNull()) {
Opa, é isso mesmo, porém o que o wasNull valida é a coluna lida anteriormente, neste caso, a coluna "git_configuration_id". Isto foi feito, porque a partir da alteração deste PR o Workspace pode deixar de ter configurações de Git, e ainda assim o Board será utilizável, porém apenas como controle de tarefas, como um Trello da vida. 

Neste caso, se a coluna anterior estiver nula, ao tentar retornar esse mapeamento de GitConfiguration(...) como era feito anteriormente teríamos nullPointerException. Desta forma que foi feita, caso não exista esta configuração de Git cadastrada, é retornado null pelo método.

2020-11-09 14:50 UTC, emiteze commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/mapper/GitConfigurationMapper.kt
> +        return if (!resultSet.wasNull()) {
Então, mas seguindo a lógica, o gitconfiguration que ele tem que fazer o deserialize é a linha atual, se vc checa pela linha anterior pra fazer o deserialize, isso é um problema, não? Não seria o caso de usar o resultSet != null mesmo? Pq ai nesse caso vc estaria checando a linha atual do resultset que tem o gitconfiguration

2020-11-09 17:47 UTC, icaroafonsozup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/mapper/GitConfigurationMapper.kt
> +        return if (!resultSet.wasNull()) {
Então, na verdade, se vc ver, o campo que eu pego acima, é o "git_configuration_id", que é o primeiro campo referente ao bloco inteiro de configuração do git. Eu não poderia utilizar "resultSet != null" porque o objeto de resultSet não é nulo, ele não possui apenas os campos relativos ao mapeamento de git configurations.

Este método, é acessado, através de uma chamada dentro de outro mapper, na classe ModuleMapper como está abaixo:

```
 fun mapModule(resultSet: ResultSet) = Module(
        id = resultSet.getString("module_id"),
        name = resultSet.getString("module_name"),
        createdAt = resultSet.getTimestamp("module_created_at").toLocalDateTime(),
        gitRepositoryAddress = resultSet.getString("module_git_repository_address"),
        helmRepository = resultSet.getString("module_helm_repository"),
        workspaceId = resultSet.getString("module_workspace_id"),
        author = mapModuleUser(resultSet),
        gitConfiguration = gitConfigurationMapper.mapGitConfiguration(resultSet), // <--- aqui
        labels = emptyList()
    )
```

como visto na parte destacada, ele envia todo o resultSet da consulta, que possui diversos campos. O que eu fiz, foi apenas validar se ele possui as informações referentes ao git_configuration.

validando pelo ID, pois se não tiver o ID não existe a configuração, daí retorno nulo.

2020-11-09 19:54 UTC, emiteze approved these changes

2020-11-10 14:04 UTC, merged