add request limiter octopipe
ZupIT/charlescd pull request #644
Opened 2020-10-30 02:51 UTC by thallesfreitaszup

Signed-off-by: Thalles Freitas <thalles.freitas@zup.com.br>

2020-11-03 17:21 UTC, cpgo approved these changes

2020-11-03 19:25 UTC, lucasbfernandes requested changes

2020-11-03 19:25 UTC, lucasbfernandes commented on install/helm-chart/charts/octopipe-charlescd/values.yaml
> +    value: "10"
I think you must change the single-file install as well

2020-11-04 18:20 UTC, lucasbfernandes submitted a review, later dismissed

2020-11-05 13:38 UTC, cpgo submitted a review, later dismissed

2020-12-02 17:03 UTC, cpgo approved these changes

2020-12-08 13:45 UTC, lucasbfernandes approved these changes

2020-12-08 13:54 UTC, merged