Vulnerabilites fixes
ZupIT/charlescd pull request #670
Opened 2020-11-12 15:12 UTC by barbararochazup

2020-11-16 21:43 UTC, pedroborgeszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/user/impl/FindAllUsersInteractorImpl.kt
> +        return convert(userService.findAll(user.name, user.email, pageRequest))
I think only user with root permission should have access to this resource

2020-11-18 12:15 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/user/impl/FindAllUsersInteractorImpl.kt
> +        return convert(userService.findAll(user.name, user.email, pageRequest))
Make sense! I made the change according to the suggestion

2020-11-18 13:53 UTC, pedroborgeszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/user/impl/FindAllUsersInteractorImpl.kt
> +        throw throw ForbiddenException()
There is an extra "throw"

2020-11-18 13:56 UTC, pedroborgeszup commented on moove/legacy-moove/src/main/kotlin/io/charlescd/moove/legacy/moove/request/configuration/CreateRegistryConfigurationRequest.kt
> +) : CreateRegistryConfigurationRequest(name, address, CreateRegistryConfigurationProvider.Azure)
I think these changes will affect the Villager module, didn't you need to do any modification there?

2020-11-18 14:25 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/user/impl/FindAllUsersInteractorImpl.kt
> +        throw throw ForbiddenException()
extra  "throw" removed

2020-11-18 14:28 UTC, barbararochazup commented on moove/legacy-moove/src/main/kotlin/io/charlescd/moove/legacy/moove/request/configuration/CreateRegistryConfigurationRequest.kt
> +) : CreateRegistryConfigurationRequest(name, address, CreateRegistryConfigurationProvider.Azure)
I removed authorId only moove request, but internally this value (according with user in authorization token) continues to be sent to villager

2020-11-18 14:40 UTC, pedroborgeszup submitted a review, later dismissed

2020-11-18 18:21 UTC, luanecavalcantizup approved these changes

2020-11-19 12:05 UTC, monicaribeiro requested changes

2020-11-24 12:53 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/UserService.kt
> +    fun findByToken(authorization: String): User {
feito

2020-12-08 20:20 UTC, monicaribeiro approved these changes

2020-12-10 14:51 UTC, monicaribeiro approved these changes

2020-12-10 14:52 UTC, Leandroqo submitted a review, later dismissed

2020-12-14 13:21 UTC, monicaribeiro approved these changes

2020-12-14 13:21 UTC, luanecavalcantizup submitted a review, later dismissed

2020-12-16 18:24 UTC, monicaribeiro submitted a review, later dismissed

2020-12-16 18:50 UTC, luanecavalcantizup submitted a review, later dismissed

2020-12-16 19:21 UTC, Leandroqo submitted a review, later dismissed

2020-12-17 19:58 UTC, merged