Compass authorization
ZupIT/charlescd pull request #674
Opened 2020-11-13 19:25 UTC by arthurpuccizup

Adding authorization scheme to all compass APIs.

2020-11-13 19:46 UTC, maycommit requested changes

2020-11-13 19:46 UTC, maycommit commented on compass/cmd/main.go
> +	enforcer, err := casbin.NewEnforcer("./auth.conf", "./policy.csv")
Esse err não deve ser tratado?

2020-11-13 19:46 UTC, maycommit commented on compass/internal/moove/moove.go
> +	Permissions json.RawMessage
Nao teve como mesmo?

2020-11-13 19:46 UTC, maycommit commented on compass/web/api/v1/v1.go
> +	_, _ = w.Write([]byte(":)"))
Isso é uma boa pratica? Nao seria mais pratico so fazer a chamada como era feito antes?

2020-11-13 20:10 UTC, arthurpuccizup commented on compass/internal/moove/moove.go
> +	Permissions json.RawMessage
Não, a gente tentou um monte de coisas mas não deu certo.

2020-11-13 20:11 UTC, arthurpuccizup commented on compass/web/api/v1/v1.go
> +	_, _ = w.Write([]byte(":)"))
A ideia é pelo menso tratar os erros no futuro, mas isso ai ficou assim acho que por engano

2020-11-13 20:12 UTC, arthurpuccizup commented on compass/cmd/main.go
> +	enforcer, err := casbin.NewEnforcer("./auth.conf", "./policy.csv")
Sim, esqueci de fazer isso, agora já foi

2020-11-13 20:22 UTC, maycommit approved these changes

2020-12-04 13:56 UTC, maycommit approved these changes

2020-12-04 14:05 UTC, maycommit approved these changes

2020-12-04 14:10 UTC, gabrielleitezup approved these changes

2020-12-04 14:16 UTC, merged