Keycloak
ZupIT/charlescd pull request #676
Opened 2020-11-16 13:06 UTC by fandrade-zup

2020-11-18 21:49 UTC, celiofilhozup submitted a review, later dismissed
lgtm

2020-11-18 21:49 UTC, celiofilhozup commented on .github/workflows/keycloak-ci.yaml
> +name: Deploy
para facilitar a leitura nas execuções poderia ser algo como keycloak-ci mesmo

2020-11-23 13:10 UTC, celiofilhozup approved these changes

2020-11-24 12:25 UTC, Leandroqo requested changes

2020-11-24 12:25 UTC, Leandroqo commented on keycloak/base-charles/login/login.ftl
> +            <!--
remove comments

2020-11-24 12:25 UTC, Leandroqo commented on keycloak/base-charles/login/login.ftl
> +                <label for="username" class="label">Enter your username or e-mail</label>
what do you think to use kc message?
```suggestion
                <label for="username" class="label">${msg("loginUsername")}</label>
```

2020-11-24 13:04 UTC, Leandroqo approved these changes

2020-11-24 16:51 UTC, celiofilhozup approved these changes
lgtm

2020-11-24 17:16 UTC, merged