Validate resources with other ids
ZupIT/charlescd pull request #681
Opened 2020-11-17 13:19 UTC by barbararochazup

2020-12-08 19:11 UTC, monicaribeiro approved these changes

2020-12-10 17:57 UTC, Leandroqo approved these changes

2020-12-16 18:20 UTC, Leandroqo approved these changes

2020-12-16 18:21 UTC, monicaribeiro requested changes

2020-12-16 18:21 UTC, monicaribeiro commented on moove/infrastructure/src/test/groovy/io/charlescd/moove/infrastructure/service/GitHubProviderServiceTest.groovy
> +        //def request = new UpdateUserRequest("John Doe", "email", "https://www.photos.com/johndoe")
Remove comment.

2020-12-16 18:21 UTC, monicaribeiro commented on moove/infrastructure/src/test/groovy/io/charlescd/moove/infrastructure/service/GitHubProviderServiceTest.groovy
> +        //1 * gitHubService.mergeBranches(gitCredentials, "repository", "master", "master", "teste")
Remove comment.

2020-12-16 18:21 UTC, monicaribeiro commented on moove/legacy-moove/src/test/groovy/io/charlescd/moove/legacy/moove/service/KeycloakServiceGroovyUnitTest.groovy
> +//TODO To remove after vulnerability-fixes pr(#670) accepted
I guess it is better to create a task instead of creating a TO DO comment. We can easily keep track of the task.

2020-12-16 18:54 UTC, barbararochazup commented on moove/legacy-moove/src/test/groovy/io/charlescd/moove/legacy/moove/service/KeycloakServiceGroovyUnitTest.groovy
> +//TODO To remove after vulnerability-fixes pr(#670) accepted
Done

2020-12-16 18:56 UTC, barbararochazup commented on moove/infrastructure/src/test/groovy/io/charlescd/moove/infrastructure/service/GitHubProviderServiceTest.groovy
> +        //1 * gitHubService.mergeBranches(gitCredentials, "repository", "master", "master", "teste")
Done

2020-12-16 18:56 UTC, barbararochazup commented on moove/infrastructure/src/test/groovy/io/charlescd/moove/infrastructure/service/GitHubProviderServiceTest.groovy
> +        //def request = new UpdateUserRequest("John Doe", "email", "https://www.photos.com/johndoe")
Done

2020-12-16 19:12 UTC, monicaribeiro submitted a review, later dismissed

2020-12-16 20:23 UTC, luanecavalcantizup approved these changes

2021-01-06 12:25 UTC, luanecavalcantizup approved these changes

2021-01-06 13:26 UTC, monicaribeiro approved these changes

2021-01-18 18:59 UTC, monicaribeiro approved these changes

2021-01-18 19:25 UTC, luanecavalcantizup submitted a review, later dismissed

2021-02-25 18:59 UTC, merged