Compass encrypt
ZupIT/charlescd pull request #700
Opened 2020-11-20 20:06 UTC by gabrielleitezup

Database field encryption on compass

2020-11-24 12:35 UTC, maycommit requested changes

2020-11-24 12:35 UTC, maycommit commented on compass/.env
> +ENCRYPTION_KEY=MAYCON
:)

2020-11-24 12:35 UTC, maycommit commented on compass/internal/configuration/configuration.go
> +	"ENCRYPTION_KEY":      "MAYCON",
:)

2020-11-24 12:35 UTC, maycommit commented on compass/internal/tests/util.go
> +func datasourceInsert(pluginSrc string) (string, datasource.Response) {
Porque essa função nao esta no datasource internal

2020-11-24 12:35 UTC, maycommit commented on compass/internal/tests/util.go
> +func actionInsert(actionType string) (string, action.Response) {
RT

2020-11-24 12:35 UTC, maycommit commented on compass/plugins/datasource/prometheus/prometheus.go
> +		var prometheusConfig map[string]string
Porque esse decode para um printf?

2020-11-24 12:35 UTC, maycommit commented on compass/plugins/datasource/prometheus/prometheus.go
> +		var prometheusConfig map[string]string
RT

2020-11-24 12:52 UTC, arthurpuccizup requested changes

2020-11-24 12:52 UTC, arthurpuccizup commented on compass/internal/action/action.go
> +func actionInsert(id, nickname, actionType, description string, config []byte, workspaceId uuid.UUID) string {
Levar essa função para dentro do arquivo queries, acho que fica mais coeso as responsabilidades

2020-11-24 12:52 UTC, arthurpuccizup commented on compass/internal/datasource/datasource.go
> +func datasourceInsert(id, name, pluginSrc string, data []byte, health bool, workspaceId uuid.UUID) string {
Mover essa função para dentro do arquivo de queries

2020-11-24 14:31 UTC, gabrielleitezup commented on compass/internal/tests/util.go
> +func datasourceInsert(pluginSrc string) (string, datasource.Response) {
Temos a função Insert no datasource internal, mas pra atender o os requisitos dos testes precisado retornar a query e o datasource com os dados predefenidos. Essa função soh server para ajudar nos testes.

2020-11-24 14:31 UTC, gabrielleitezup commented on compass/internal/tests/util.go
> +func actionInsert(actionType string) (string, action.Response) {
Temos a função Insert no datasource internal, mas pra atender o os requisitos dos testes precisado retornar a query e o datasource com os dados predefenidos. Essa função soh server para ajudar nos testes.

2020-11-24 17:29 UTC, maycommit submitted a review, later dismissed

2020-11-26 20:10 UTC, maycommit approved these changes

2020-11-26 20:11 UTC, arthurpuccizup approved these changes

2020-12-07 14:14 UTC, arthurpuccizup approved these changes

2020-12-07 14:15 UTC, maycommit approved these changes

2020-12-07 14:21 UTC, merged