The 'delete' button should be inactive when the circle is active
ZupIT/charlescd pull request #706
Opened 2020-11-25 12:13 UTC by luanecavalcantizup

2020-11-27 13:36 UTC, pedroborgeszup commented on ui/src/modules/Circles/Comparation/Item/helpers.ts
> +  } else if (isDefaultCircle(circle?.name) && hasDeploy(circle)) {
These 2 conditions above can be reduced to just 1. Ex. If (isDefaultCircle (circle? .Name))

2020-11-27 15:07 UTC, luanecavalcantizup commented on ui/src/modules/Circles/Comparation/Item/helpers.ts
> +  } else if (isDefaultCircle(circle?.name) && hasDeploy(circle)) {
I think having different messages for when default circle is active and when is inactive is more descriptive. Jose (the UX) did the design in invision for these cases. What do you think?

2020-11-27 18:06 UTC, pedroborgeszup commented on ui/src/modules/Circles/Comparation/Item/helpers.ts
> +  } else if (isDefaultCircle(circle?.name) && hasDeploy(circle)) {
Ok! 👍

2020-12-03 20:37 UTC, monicaribeiro requested changes

2020-12-03 20:37 UTC, monicaribeiro commented on moove/web/src/main/resources/locale/messages.properties
> +deploymet.active= There is an active deployment for the circle you want to delete
This circle has an active deployment.

2020-12-03 20:37 UTC, monicaribeiro commented on moove/web/src/main/resources/locale/messages_pt_BR.properties
> +deployment.active=Existe um deployment ativo para o círculo que deseja apagar
```suggestion
deployment.active=Este círculo possui uma implantação ativa.
```

2020-12-03 21:19 UTC, monicaribeiro submitted a review, later dismissed

2020-12-07 21:56 UTC, Leandroqo submitted a review, later dismissed

2020-12-08 19:01 UTC, monicaribeiro approved these changes

2020-12-10 14:53 UTC, Leandroqo approved these changes

2020-12-14 16:34 UTC, monicaribeiro submitted a review, later dismissed

2020-12-14 17:07 UTC, Leandroqo approved these changes

2020-12-16 13:17 UTC, monicaribeiro approved these changes

2020-12-16 20:54 UTC, merged