Script dynamic id default
ZupIT/charlescd pull request #709
Opened 2020-11-25 16:57 UTC by thallesfreitaszup

2020-11-30 20:14 UTC, lucasbfernandes requested changes

2020-12-01 13:55 UTC, thallesfreitaszup commented on butler/src/resources/scripts/upgrades/0.4.1-0.4.2/migration.js
> +import PG from 'pg'
Done

2020-12-01 18:42 UTC, cpgo submitted a review, later dismissed

2020-12-01 19:09 UTC, lucasbfernandes approved these changes

2021-01-19 19:25 UTC, closed without merging