Add Infinite scroll
ZupIT/charlescd pull request #719
Opened 2020-11-27 12:15 UTC by washingtonsoares

2020-12-01 18:19 UTC, bCatanant submitted a review, later dismissed

2020-12-01 18:57 UTC, ifdouglas requested changes

2020-12-01 18:57 UTC, ifdouglas commented on ui/src/core/components/InfiniteScroll/index.tsx
> +  children: React.ReactNode;
```suggestion
  children: ReactNode;
```

2020-12-01 18:57 UTC, ifdouglas commented on ui/src/core/components/InfiniteScroll/index.tsx
> +  loader: React.ReactNode;
```suggestion
  children: ReactNode;
```

2020-12-01 18:57 UTC, ifdouglas commented on ui/src/core/components/InfiniteScroll/index.tsx
> +  const childrenLength = React.Children.count(children);
```suggestion
  const childrenLength = Children.count(children);
```

2020-12-01 18:57 UTC, ifdouglas commented on ui/src/core/hooks/useInfiniteScroll.ts
> +  React.RefObject<LoaderElementType>,
```suggestion
  RefObject<LoaderElementType>,
```

2020-12-01 18:57 UTC, ifdouglas commented on ui/src/core/hooks/useInfiniteScroll.ts
> +  React.RefObject<ScrollElementType>,
```suggestion
  RefObject<ScrollElementType>,
```

2020-12-01 18:57 UTC, ifdouglas commented on ui/src/core/providers/circle.ts
> +  const defaultPageSize = 50;
I've seeing that this value `50` will be the default size for all pages in Charles, alright?
We could centralize those in one place.

2020-12-01 18:57 UTC, ifdouglas commented on ui/src/modules/Circles/Menu/MenuItem.tsx
> +    <div>
Is it possible to use a `<Fragment>` here instead of a `<div>`?

2020-12-01 18:57 UTC, ifdouglas commented on ui/src/modules/Circles/Menu/index.tsx
> +  children: React.ReactNode;
```suggestion
  children: ReactNode;
```

2020-12-01 18:57 UTC, ifdouglas commented on ui/src/modules/Circles/styled.ts
> +  ref: React.RefObject<HTMLElement>;
```suggestion
  ref: RefObject<HTMLElement>;
```

2020-12-01 18:59 UTC, ifdouglas requested changes

2020-12-01 18:59 UTC, ifdouglas commented on ui/src/modules/Circles/Menu/Loaders/MenuItem.spec.tsx
> +  render(<MenuItem id="1" name="circle" />);
Put `id` and `name` in a const props to call in all tests

2020-12-01 19:06 UTC, washingtonsoares commented on ui/src/modules/Circles/Menu/Loaders/MenuItem.spec.tsx
> +  render(<MenuItem id="1" name="circle" />);
IMHO, I disagree. There are no advantages to doing this type of abstraction for tests as simple as these

2020-12-02 14:01 UTC, bCatanant approved these changes

2020-12-02 19:20 UTC, Leandroqo submitted a review, later dismissed

2020-12-03 11:25 UTC, ifdouglas commented on ui/src/modules/Circles/Menu/Loaders/MenuItem.spec.tsx
> +  render(<MenuItem id="1" name="circle" />);
When we repeat something we did not lose nothing centering it

2020-12-03 11:27 UTC, ifdouglas approved these changes

2020-12-16 20:52 UTC, barbararochazup approved these changes

2020-12-16 21:00 UTC, luanecavalcantizup submitted a review, later dismissed

2021-01-04 18:46 UTC, pedroborgeszup approved these changes

2021-01-05 19:58 UTC, merged