Remove old components when deploying on a circle (Override deployment)
ZupIT/charlescd pull request #721
Opened 2020-11-27 19:02 UTC by cpgo

By default all deployments performed on a circle will always remove the old components.
If everything work as expected we can remove the undeployment call that Moove performs on each deployment since its always handled by Butler.

2020-11-27 19:08 UTC, lucasbfernandes requested changes

2020-11-27 19:08 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/octopipe/request-builder.ts
>        }
Maybe separate these two implementations in different methods?

You could change the deployment object to:

```
{
...
unusedDeployments: deployment.defaultCircle ? defaultUnusedVersions() : circleUnusedVersions()
}
```

2020-11-27 19:08 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/spinnaker/pipeline-builder.ts
> +      return getDeleteUnusedStage(component, deployment.cdConfiguration, this.currentStageId++, evalStageId, deployment.circleId)
Maybe separate these two implementations in different methods?

2020-11-27 19:08 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/deployment.utils.ts
> +}
Why have this method if you can put `isSameName(...)` inline on the removedComponents method?

2020-11-27 19:08 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/deployment.utils.ts
> +}
Why have this method if you can put `isSameNameAndDifferentVersion(...)` inline on the removedComponents method?

2020-11-27 19:08 UTC, lucasbfernandes commented on butler/src/app/v2/core/integrations/utils/deployment.utils.ts
> +const isSameNameAndDifferenteVersion = (deploymentComponent: DeploymentComponent, activeComponent: Component): boolean => {
Typo here: Different not Differente

2020-11-30 15:10 UTC, thallesfreitaszup requested changes

2020-11-30 15:10 UTC, thallesfreitaszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/deployment/impl/CreateDeploymentInteractorImpl.kt
> -            undeployActiveDeploymentFromCircleIfExists(deployment, workspaceId)
Agora que a chamada do undeploy foi removida do moove acho que seria interessante no callback do deploy atualizar os status dos deployments anteriores para NOT_DEPLOYED, algo que tinhamos no callback do undeploy. Como isso foi removido todo deploy ficaria com status DEPLOYED no moove.

2020-11-30 17:01 UTC, thallesfreitaszup approved these changes

2020-11-30 18:41 UTC, lucasbfernandes commented on moove/application/src/main/kotlin/io/charlescd/moove/application/deployment/impl/CreateDeploymentInteractorImpl.kt
> -            undeployActiveDeploymentFromCircleIfExists(deployment, workspaceId)
Verdade... Temos que ver essa questão dos status na exibiçao da tela. Sem o undeploy via moove o status vai ficar DEPLOYED até sumir (acho)

2020-12-01 18:45 UTC, thallesfreitaszup approved these changes

2020-12-04 13:10 UTC, lucasbfernandes approved these changes

2020-12-04 13:24 UTC, merged