Security restrict access users data
ZupIT/charlescd pull request #724
Opened 2020-11-30 20:46 UTC by icaroafonsozup

2020-12-10 14:59 UTC, monicaribeiro requested changes

2020-12-10 14:59 UTC, monicaribeiro commented on moove/api/src/main/kotlin/io/charlescd/moove/api/controller/V2UserController.kt
> +    @GetMapping("/id/{id}")
Remover este endpoint, pois o desenvolvido abaixo está resolvendo o problema levantado.

2020-12-10 19:33 UTC, icaroafonsozup commented on moove/api/src/main/kotlin/io/charlescd/moove/api/controller/V2UserController.kt
> +    @GetMapping("/id/{id}")
Endpoint removido conforme sugerido.

2021-01-06 18:37 UTC, ifdouglas requested changes

2021-01-06 18:37 UTC, ifdouglas commented on ui/src/modules/Workspaces/hooks.ts
> +      if (isRoot()) {
Roles conditions is better outside the hook, because hooks are made to be reusable.

2021-01-07 11:23 UTC, ifdouglas approved these changes
UI approved

2021-01-11 19:37 UTC, monicaribeiro approved these changes

2021-01-20 18:27 UTC, ifdouglas requested changes

2021-01-20 18:27 UTC, ifdouglas commented on ui/src/modules/Users/__tests__/hooks.spec.tsx
> +  expect(response).not.toBeUndefined();
I think this is not needed, because the previous assertion do this job alone.

2021-01-20 18:27 UTC, ifdouglas commented on ui/src/modules/Users/__tests__/hooks.spec.tsx
> +  expect(response).not.toBeUndefined();
I think this is not needed, because the previous assertion do this job alone.

2021-01-20 18:43 UTC, monicaribeiro approved these changes

2021-01-20 19:07 UTC, ifdouglas approved these changes

2021-01-20 20:16 UTC, monicaribeiro approved these changes

2021-01-21 17:05 UTC, merged