added percentage strategy
ZupIT/charlescd pull request #726
Opened 2020-12-01 13:37 UTC by lucassaleszup

Signed-off-by: Lucas Sales <lucas.sales@zup.com.br>

2020-12-01 21:57 UTC, ifdouglas requested changes

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/assets/svg/alternate-down.svg
> +        <path d="M4.66683333,5.3335 C4.49616667,5.3335 4.3255,5.26816667 4.1955,5.13816667 L0.1955,1.13816667 C-0.0651666667,0.8775 -0.0651666667,0.456166667 0.1955,0.1955 C0.456166667,-0.0651666667
Change all the `id`s inside a SVG to avoid conflict when render. Make a join with the name of the SVG is a good choice. Ex: `path-1-alternate-down` or `path-alternate-down`

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/assets/svg/alternate-down.svg
> +        <g id="Group" transform="translate(-3.000000, -6.000000)">
```suggestion
        <g id="Group-alternate-down" transform="translate(-3.000000, -6.000000)">
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/assets/svg/manually.svg
> +        <path d="M14,14 C14.3686667,14 14.6666667,14.298 14.6666667,14.6666667 C14.6666667,15.0353333 14.3686667,15.3333333 14,15.3333333 L2,15.3333333 C1.632,15.3333333 1.33333333,15.0353333 1.33333
Change `id`

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/assets/svg/percentage.svg
> +        <path d="M9.66666667,7.33333333 C10.9533333,7.33333333 12,8.38 12,9.66666667 C12,10.9533333 10.9533333,12 9.66666667,12 C8.38,12 7.33333333,10.9533333 7.33333333,9.66666667 C7.33333333,8.38 8
Change `id`

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/assets/svg/percentage.svg
> +                    <mask id="mask-2" fill="white">
Change `id`

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/assets/svg/percentage.svg
> +        <g id="Group" transform="translate(-2.000000, -2.000000)">
Change `id`

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/assets/svg/up.svg
> +        <g id="Group" transform="translate(-3.000000, -4.000000)">
Change `id`

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/assets/svg/up.svg
> +        <path d="M4.66683333,5.3335 C4.49616667,5.3335 4.3255,5.26816667 4.1955,5.13816667 L0.1955,1.13816667 C-0.0651666667,0.8775 -0.0651666667,0.456166667 0.1955,0.1955 C0.456166667,-0.0651666667
Change `id`

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/providers/circle.ts
> +  return baseRequest(`${endpoint}/${id}/percentage`, payload, {
Is this patch updating always the name and the percentage? This logic is confusing for me

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/Percentage.tsx
> +            title=""
Is title really empty?

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/Percentage.tsx
> +    limitPercentage === 0 && (
This logic is reused, so maybe creating a `const` with this and call in all places will be a good option.

```suggestion
    const isUnable = !isEditing && limitPercentage === 0
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/components/Button/Rounded/styled.ts
> +};
```suggestion
export enum RADIUS {
  small = '15px',
  medium = '20px',
  normal = '30px'
}
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/components/Button/Rounded/styled.ts
> +  border-radius: ${({ size }) => getButtonRadius(size)};
```suggestion
  border-radius: ${({ size }) => RADIUS[size]};
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/components/Button/Rounded/styled.ts
> +  padding: ${({ size }) => getButtonPadding(size)};
```suggestion
  padding: ${({ size }) => PADDING[size]};
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/components/Button/Rounded/styled.ts
> +};
```suggestion
export enum PADDING {
  small = '9px 18px',
  medium = '12px 25px',
  normal = '15px 33px'
};
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/components/Button/Rounded/styled.ts
> +};
```suggestion
export enum HEIGHT {
  small = '30px',
  medium = '40px',
  normal = '50px'
};
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/core/components/Button/Rounded/styled.ts
> +  height: ${({ size }) => getButtonHeight(size)};
```suggestion
  height: ${({ size }) => HEIGHT[size]};
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/Slider.tsx
> +        ></Styled.Slider>
```suggestion
        <Styled.Slider
          type="range"
          data-testid="slider-input"
          value={sliderValue}
          onChange={e => handleChange(e.target.value)}
          max={limitValue}
        />
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/Percentage.spec.tsx
> +  fireEvent.click(listContainerButton)
```suggestion
  userEvent.click(listContainerButton)
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/Percentage.spec.tsx
> +  fireEvent.click(submitButton)
```suggestion
  userEvent.click(submitButton)
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/Percentage.spec.tsx
> +  fireEvent.change(SliderInput, {
```suggestion
  userEvent.type(SliderInput, {
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/Percentage.spec.tsx
> +  fireEvent.click(submitButton)
```suggestion
  userEvent.click(submitButton)
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/Layer/Release.tsx
> +    return false;
Make sense if change to this?
```suggestion
    return (!circle?.id || !releaseEnabled)
```

2020-12-01 21:57 UTC, ifdouglas commented on ui/src/modules/Circles/Comparation/Item/Percentage/__tests__/CirclePercentageList.spec.tsx
> +    fireEvent.click(CirclePercentageListContainerButton)
```suggestion
    userEvent.click(CirclePercentageListContainerButton)
```

2020-12-02 13:51 UTC, lucassaleszup commented on ui/src/core/assets/svg/alternate-down.svg
> +        <g id="Group" transform="translate(-3.000000, -6.000000)">
alterado

2020-12-02 13:54 UTC, lucassaleszup commented on ui/src/core/assets/svg/manually.svg
> +        <path d="M14,14 C14.3686667,14 14.6666667,14.298 14.6666667,14.6666667 C14.6666667,15.0353333 14.3686667,15.3333333 14,15.3333333 L2,15.3333333 C1.632,15.3333333 1.33333333,15.0353333 1.33333
alterado

2020-12-02 13:54 UTC, lucassaleszup commented on ui/src/core/assets/svg/percentage.svg
> +        <path d="M9.66666667,7.33333333 C10.9533333,7.33333333 12,8.38 12,9.66666667 C12,10.9533333 10.9533333,12 9.66666667,12 C8.38,12 7.33333333,10.9533333 7.33333333,9.66666667 C7.33333333,8.38 8
alterado

2020-12-02 13:55 UTC, lucassaleszup commented on ui/src/core/assets/svg/percentage.svg
> +                    <mask id="mask-2" fill="white">
alterado

2020-12-02 13:55 UTC, lucassaleszup commented on ui/src/core/assets/svg/percentage.svg
> +        <g id="Group" transform="translate(-2.000000, -2.000000)">
alterado

2020-12-02 13:55 UTC, lucassaleszup commented on ui/src/core/assets/svg/up.svg
> +        <g id="Group" transform="translate(-3.000000, -4.000000)">
alterado

2020-12-02 13:55 UTC, lucassaleszup commented on ui/src/core/assets/svg/up.svg
> +        <path d="M4.66683333,5.3335 C4.49616667,5.3335 4.3255,5.26816667 4.1955,5.13816667 L0.1955,1.13816667 C-0.0651666667,0.8775 -0.0651666667,0.456166667 0.1955,0.1955 C0.456166667,-0.0651666667
alterado

2020-12-02 13:58 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/Percentage.tsx
> +            title=""
according to the design, yes.

2020-12-02 13:59 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/Percentage.tsx
> +    limitPercentage === 0 && (
Done

2020-12-02 14:02 UTC, lucassaleszup commented on ui/src/core/components/Button/Rounded/styled.ts
> +};
done

2020-12-02 14:02 UTC, lucassaleszup commented on ui/src/core/components/Button/Rounded/styled.ts
> +  border-radius: ${({ size }) => getButtonRadius(size)};
done

2020-12-02 14:02 UTC, lucassaleszup commented on ui/src/core/components/Button/Rounded/styled.ts
> +  padding: ${({ size }) => getButtonPadding(size)};
done

2020-12-02 14:02 UTC, lucassaleszup commented on ui/src/core/components/Button/Rounded/styled.ts
> +};
done

2020-12-02 14:03 UTC, lucassaleszup commented on ui/src/core/components/Button/Rounded/styled.ts
> +};
done

2020-12-02 14:03 UTC, lucassaleszup commented on ui/src/core/components/Button/Rounded/styled.ts
> +  height: ${({ size }) => getButtonHeight(size)};
done

2020-12-02 14:04 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/Slider.tsx
> +        ></Styled.Slider>
done

2020-12-02 14:05 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/Percentage.spec.tsx
> +  fireEvent.click(listContainerButton)
done

2020-12-02 14:05 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/Percentage.spec.tsx
> +  fireEvent.click(submitButton)
done

2020-12-02 14:05 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/Percentage.spec.tsx
> +  fireEvent.change(SliderInput, {
done

2020-12-02 14:05 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/Percentage.spec.tsx
> +  fireEvent.click(submitButton)
done

2020-12-02 14:31 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/Layer/Release.tsx
> +    return false;
no, because if the first condition is true (case of editing) the button will always be enabled.

2020-12-02 14:32 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/Layer/Release.tsx
> +    return false;
and we need to check if the Id exists as well as the percentage available.

2020-12-02 14:33 UTC, lucassaleszup commented on ui/src/modules/Circles/Comparation/Item/Percentage/__tests__/CirclePercentageList.spec.tsx
> +    fireEvent.click(CirclePercentageListContainerButton)
done

2020-12-02 17:28 UTC, Leandroqo requested changes

2020-12-02 17:28 UTC, Leandroqo commented on ui/src/core/assets/svg/alert.svg
> +                        <use xlink:href="#path-1"></use>
change path-1 to path-alert.

2020-12-02 17:28 UTC, Leandroqo commented on ui/src/core/assets/svg/alert.svg
> +                    <use id="Icon-Alert-Triangle" fill="#FFD60A" xlink:href="#path-1"></use>
```suggestion
                    <use id="Icon-Alert-Triangle" fill="currentColor" xlink:href="#path-1"></use>
```

2020-12-02 17:28 UTC, Leandroqo commented on ui/src/core/assets/svg/alternate-down.svg
> +                <use id="Icon-Chevron-Down" fill="#B9B9BE" xlink:href="#path-1-alternate-down"></use>
```suggestion
                <use id="Icon-Chevron-Down" fill="currentColor" xlink:href="#path-1-alternate-down"></use>
```

2020-12-02 17:28 UTC, Leandroqo commented on ui/src/core/assets/svg/manually.svg
> +            <use id="Icon-Edit" fill="#B9B9BE" xlink:href="#path-1-manually"></use>
```suggestion
            <use id="Icon-Edit" fill="currentColor" xlink:href="#path-1-manually"></use>
```

2020-12-02 17:28 UTC, Leandroqo commented on ui/src/core/assets/svg/percentage.svg
> +                    <use id="Icon-Percent" fill="#B9B9BE" xlink:href="#path-1-percentage"></use>
```suggestion
                    <use id="Icon-Percent" fill="currentColor" xlink:href="#path-1-percentage"></use>
```

2020-12-02 17:28 UTC, Leandroqo commented on ui/src/core/assets/svg/up.svg
> +                <use id="Icon-Chevron-Up" fill="#B9B9BE" transform="translate(4.666833, 2.666750) scale(1, -1) translate(-4.666833, -2.666750) " xlink:href="#path-1-up"></use>
```suggestion
                <use id="Icon-Chevron-Up" fill="currentColor" transform="translate(4.666833, 2.666750) scale(1, -1) translate(-4.666833, -2.666750) " xlink:href="#path-1-up"></use>
```

2020-12-02 17:28 UTC, Leandroqo commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/Slider.tsx
> +            validate: value => {
what do you think of putting this in utils?

2020-12-02 18:16 UTC, Leandroqo approved these changes

2020-12-15 19:30 UTC, bCatanant approved these changes

2021-01-05 13:42 UTC, ifdouglas submitted a review, later dismissed

2021-01-11 13:29 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/Circle.java
> +    public static Circle from(KeyMetadata keyMetadata) {
Verify if argument is null/invalid and throw `IllegalArgumentException` if so.

2021-01-11 13:32 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    public void setPercentage(Integer percentage) {
This must not allow values lower than 0 and bigger than 100. This should be verified here and also throw `IllegalArgumentException` if so.

2021-01-11 13:33 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/api/request/SegmentationRequest.java
> +        this.percentage = percentage;
This must not allow values lower than 0 and bigger than 100. This should be verified here and also throw `IllegalArgumentException` if so.

2021-01-11 13:35 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    public int sumPercentage(Integer percentageToSum) {
The result of sum should also be verified before change the variable. Not < 0 and not > 100.

2021-01-11 14:18 UTC, eliasalveszup commented on circle-matcher/src/test/groovy/io/charlescd/circlematcher/domain/service/RandomServiceImplTest.groovy
> +    def "should return random number in limits"() {
This test could use a loop to test more times, and the correct check is `result >=0 && result <=100`

2021-01-14 14:15 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    public void setPercentage(Integer percentage) {
the validation  was inserted on request, it is necessary to add here too? also the percentage could be null on circles on csv and regular circles.

2021-01-14 14:16 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    public int sumPercentage(Integer percentageToSum) {
done

2021-01-14 14:26 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/Circle.java
> +    public static Circle from(KeyMetadata keyMetadata) {
This validation is done here with the ifPresent, it is necessary to do inside the class? 
> this.getCircleByPercentage(percentageMatched)
                        .ifPresent(keyMetadata -> matched.add(Circle.from(keyMetadata)));

2021-01-14 14:58 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/Circle.java
> +    public static Circle from(KeyMetadata keyMetadata) {
The use of method is ok (null safe), but it's a good practice to avoid this kind of risk encapsulating this validation, because you cannot guarantee that everyone that will use this method has this concern.

2021-01-14 15:03 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    public void setPercentage(Integer percentage) {
Is it guaranteed that the use of this attribute will only be by request dto? If yes, ok. If not, the verification is a good practice (in case of not null).

2021-01-14 17:34 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/Circle.java
> +    public static Circle from(KeyMetadata keyMetadata) {
Agreed.Done

2021-01-14 17:35 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/KeyMetadata.java
> +    public void setPercentage(Integer percentage) {
It's not.Done

2021-01-14 17:35 UTC, thallesfreitaszup commented on circle-matcher/src/test/groovy/io/charlescd/circlematcher/domain/service/RandomServiceImplTest.groovy
> +    def "should return random number in limits"() {
done

2021-01-15 14:07 UTC, eliasalveszup submitted a review, later dismissed
Focused on backend changes.

2021-01-19 20:10 UTC, ifdouglas submitted a review, later dismissed

2021-03-11 13:52 UTC, Leandroqo requested changes

2021-03-11 13:52 UTC, Leandroqo commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/CreateSegments.spec.tsx
> +test("render CreateSegments with manual session active", async () => {
the above test has the same name

2021-03-11 13:52 UTC, Leandroqo commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/__tests__/CreateSegments.spec.tsx
> +  act(() => {
is it necessary to wrap the userEvent in one act in this case, since the next event is a waitFor?

2021-03-11 14:53 UTC, Leandroqo approved these changes

2021-03-11 14:55 UTC, bCatanant submitted a review, later dismissed

2021-03-11 21:24 UTC, eliasalveszup approved these changes
Ok for backend side

2021-03-11 22:49 UTC, emiteze approved these changes

2021-03-11 22:49 UTC, emiteze commented on moove/application/src/main/kotlin/io/charlescd/moove/application/circle/request/CreateCircleWithPercentageRequest.kt
> +package io.charlescd.moove.application.circle.request
Missing license header

2021-03-11 22:49 UTC, emiteze commented on moove/infrastructure/src/main/resources/db/changelog/includes/20201007113800_alter_table_circles_add_percentage_column.yaml
> +      comment: "Adding percentage column to ci"
Fix description on this migration

2021-03-11 22:51 UTC, emiteze requested changes
Please check my comments, i approved instead of asking for changes

2021-03-12 12:42 UTC, thallesfreitaszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/circle/request/CreateCircleWithPercentageRequest.kt
> +package io.charlescd.moove.application.circle.request
done

2021-03-12 12:42 UTC, thallesfreitaszup commented on moove/infrastructure/src/main/resources/db/changelog/includes/20201007113800_alter_table_circles_add_percentage_column.yaml
> +      comment: "Adding percentage column to ci"
done

2021-03-16 18:23 UTC, bCatanant commented on ui/src/core/components/Form/Number/helper.ts
> +export const isNumber = (value: string) => /[0-9]/.test(value);
Add certificate

2021-03-16 18:23 UTC, bCatanant commented on ui/src/modules/Circles/Comparation/Item/CreateSegments/Slider.tsx
> +import React, { useEffect, useState } from 'react';
Add certificate

2021-03-16 18:27 UTC, bCatanant approved these changes

2021-03-16 19:10 UTC, eliasalveszup submitted a review, later dismissed

2021-03-16 19:34 UTC, emiteze approved these changes

2021-03-16 20:20 UTC, bCatanant approved these changes

2021-03-16 20:42 UTC, angelicalimazup approved these changes

2021-03-17 11:19 UTC, merged