Payload validation
ZupIT/charlescd pull request #738
Opened 2020-12-08 20:36 UTC by leandrorodrigueszup

2020-12-15 19:00 UTC, cpgo submitted a review, later dismissed

2020-12-15 19:11 UTC, lucasbfernandes requested changes

2020-12-15 19:11 UTC, lucasbfernandes commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/validation/NodeValidator.java
> +    }
Maybe separate this is different methods?

```
private boolean validate(Node node) {
    if (node.getType() == NodeType.CLAUSE) {
        return node.isValidClauseType() && validateClauses(node.getClauses());
    } else {
        return node.isValidRuleType();
    }
}

private boolean validateClauses(clauses) {
    boolean valid = false;
    for (var clause : clauses) {
        valid = validate(clause);
        if (!valid) {
            break;
        }
    }
    return valid;
}
```

2020-12-16 14:09 UTC, leandrorodrigueszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/domain/validation/NodeValidator.java
> +    }
Done

2020-12-17 17:10 UTC, cpgo approved these changes

2020-12-17 17:16 UTC, lucasbfernandes approved these changes

2021-01-07 16:48 UTC, thallesfreitaszup approved these changes

2021-01-07 22:43 UTC, cpgo approved these changes

2021-01-08 12:16 UTC, merged