Fix octopipe overriding helm objects
ZupIT/charlescd pull request #739
Opened 2020-12-09 14:15 UTC by thallesfreitaszup

2020-12-15 17:47 UTC, lucasbfernandes approved these changes

2020-12-17 19:06 UTC, cpgo requested changes
Maybe we should also write a new test that would fail without this fix to avoid any regressions.

2021-01-07 11:06 UTC, cpgo approved these changes

2021-01-07 11:06 UTC, cpgo approved these changes

2021-01-15 14:12 UTC, eliasalveszup commented on octopipe/pkg/template/helm/helm.go
> +	 if err != nil {
Wrong identation

2021-01-15 14:14 UTC, eliasalveszup approved these changes

2021-01-22 18:30 UTC, merged