Test connection with registries (AWS, Harbor, Docker Hub, Azure)
ZupIT/charlescd pull request #748
Opened 2020-12-11 20:30 UTC by luanecavalcantizup

*GCR registry is already merged into master.

### BACKEND
Validate connection with registries.

### FRONTEND
Test connection with a registry (example)
![Captura de Tela (323)](https://user-images.githubusercontent.com/68286947/97987075-7724fc80-1db9-11eb-9b44-b317dcdcd7d3.png)

Verify if registry is valid (example)
![Captura de Tela (322)](https://user-images.githubusercontent.com/68286947/97986766-f239e300-1db8-11eb-90af-b532301440e1.png)

2020-12-15 12:23 UTC, barbararochazup commented on villager/src/main/java/io/charlescd/villager/service/impl/RegistryServiceImpl.java
> +        if (response == null) {
só a titulo de curiosidade, qual a vantagem de usar == ao inves do Objects.isNull?

2020-12-15 12:26 UTC, barbararochazup commented on villager/src/main/java/io/charlescd/villager/service/impl/RegistryServiceImpl.java
> -                validateGCPResponse(response);
pq foi retirado a implementação do GCP e o retorno de erro dos outros types ainda não implementados?

2020-12-15 12:29 UTC, barbararochazup reviewed
Only some questions

2020-12-15 12:37 UTC, lucassaleszup commented on villager/src/main/java/io/charlescd/villager/service/impl/RegistryServiceImpl.java
> +        if (response == null) {
Golang feelings, Objects.isNull is better, tks.

2020-12-15 12:41 UTC, lucassaleszup commented on villager/src/main/java/io/charlescd/villager/service/impl/RegistryServiceImpl.java
> -                validateGCPResponse(response);
because all five projects have been implemented, and all of them use the validateGenericV2ApiResponse method.

only requests with an unknown registry type will return the error 
`IllegalStateException("Registry` type not supported!");`

2020-12-15 13:15 UTC, barbararochazup submitted a review, later dismissed

2020-12-15 13:28 UTC, monicaribeiro requested changes

2020-12-15 13:28 UTC, monicaribeiro commented on villager/src/main/java/io/charlescd/villager/service/impl/RegistryServiceImpl.java
>          if (Objects.isNull(response)) {
```suggestion
        if (Objects.isNull(response) || response.isEmpty()) {
```

2020-12-15 13:28 UTC, monicaribeiro commented on villager/src/main/java/io/charlescd/villager/service/impl/RegistryServiceImpl.java
> +    private boolean notFoundImageError(int status, RegistryType type) {
```suggestion
    private boolean isNotFoundImageError(int status, RegistryType type) {
```

2020-12-15 13:28 UTC, monicaribeiro commented on villager/src/test/java/io/charlescd/villager/interactor/registry/impl/TestRegistryConfigInteractorImplTest.java
>  public class TestRegistryConfigInteractorImplTest {
```suggestion
public class RegistryConfigInteractorImplTest {
```

2020-12-15 14:21 UTC, barbararochazup submitted a review, later dismissed

2020-12-15 17:54 UTC, monicaribeiro submitted a review, later dismissed

2020-12-17 19:08 UTC, barbararochazup submitted a review, later dismissed

2020-12-17 20:27 UTC, monicaribeiro submitted a review, later dismissed

2021-01-05 14:00 UTC, lucassaleszup commented on ui/package.json
> +    "@types/uuid": "^8.3.0",
remove

2021-01-05 14:01 UTC, lucassaleszup commented on ui/package.json
> +    "uuid": "^8.3.2"
remove

2021-01-05 14:02 UTC, lucassaleszup commented on ui/src/modules/Settings/Credentials/Sections/Registry/hooks.ts
> +          setResponse(uuidv4());
remove

2021-01-05 14:02 UTC, ifdouglas requested changes

2021-01-05 14:02 UTC, ifdouglas commented on ui/src/modules/Settings/Credentials/Sections/Registry/hooks.ts
> +          setResponse(uuidv4());
Do we need this uuid?

2021-01-05 19:05 UTC, ifdouglas submitted a review, later dismissed

2021-01-07 18:48 UTC, barbararochazup submitted a review, later dismissed

2021-01-11 19:31 UTC, closed without merging