Compass structured error
ZupIT/charlescd pull request #750
Opened 2020-12-15 12:33 UTC by maycommit

2021-01-14 18:11 UTC, gabrielleitezup requested changes

2021-01-14 18:11 UTC, gabrielleitezup commented on compass/internal/metricsgroup/metricsgroup.go
> +	// "errors"
Remove comment

2021-01-14 21:57 UTC, gabrielleitezup requested changes

2021-01-14 21:57 UTC, gabrielleitezup commented on compass/internal/metricsgroupaction/actionexecution.go
> +			WithOperations("SetExecutionSuccess.validateActionCanFinish")
```suggestion
			WithOperations("SetExecutionSuccess.Save")
```

2021-01-14 21:57 UTC, gabrielleitezup commented on compass/web/api/api.go
>  package api
Copyright removed

2021-01-14 21:57 UTC, gabrielleitezup commented on compass/web/api/middleware.go
> +		if err != nil {
The `if` should check the `enforcerErr`, not the `err`

2021-01-14 21:57 UTC, gabrielleitezup commented on compass/web/api/v1.go
> +		s.HandleFunc(fmt.Sprintf("%s/{metricGroupID}", path), metricsgroup.UpdateName(api.metricsGroupMain)).Methods("PATCH") // TODO: Discutir necessidade desse patch
Keep TODO?

2021-01-15 12:31 UTC, arthurpuccizup commented on compass/web/api/v1.go
> +		s.HandleFunc(fmt.Sprintf("%s/{metricGroupID}", path), metricsgroup.UpdateName(api.metricsGroupMain)).Methods("PATCH") // TODO: Discutir necessidade desse patch
Lets keep, for later discussion

2021-01-15 12:32 UTC, arthurpuccizup commented on compass/web/api/middleware.go
> +		if err != nil {
Done

2021-01-15 12:32 UTC, arthurpuccizup commented on compass/web/api/api.go
>  package api
Done

2021-01-15 12:32 UTC, arthurpuccizup commented on compass/internal/metricsgroupaction/actionexecution.go
> +			WithOperations("SetExecutionSuccess.validateActionCanFinish")
Done

2021-01-15 12:32 UTC, arthurpuccizup commented on compass/internal/metricsgroup/metricsgroup.go
> +	// "errors"
Done

2021-01-15 18:06 UTC, gabrielleitezup approved these changes

2021-01-20 17:35 UTC, gabrielleitezup requested changes

2021-01-20 17:35 UTC, gabrielleitezup commented on compass/internal/health/health.go
> +		return nil, err.WithOperations("getResultQuery.Lookup")
```suggestion
		return nil, err.WithOperations("getComponentsErrorPercentage.GetMooveComponents")
```

2021-01-20 17:41 UTC, gabrielleitezup approved these changes

2021-01-20 17:41 UTC, icaroafonsozup approved these changes

2021-01-20 17:46 UTC, merged