Hermes Initial Structure
ZupIT/charlescd pull request #765
Opened 2020-12-18 13:55 UTC by gabrielleitezup

Hermes folder structure
https://app.clubhouse.io/charle/story/42805/cria%C3%A7%C3%A3o-da-estrutura-do-projeto-hermes

2021-01-05 17:03 UTC, barbararochazup commented on hermes/resources/hermes/cometarios.txt
> +- Controle de threads para o consumo da fila
acho que seria legal remover esse arquivo depois

2021-01-05 17:04 UTC, barbararochazup commented on hermes/resources/hermes/scripts.sql
> +-- Hermes
precisa manter esse file? a mesma estrutura está no arquivo inicial do migration

2021-01-05 17:05 UTC, barbararochazup requested changes
algumas duvidas e sugestões

2021-01-19 17:52 UTC, arthurpuccizup requested changes

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/internal/configuration/configuration.go
> +	"ENCRYPTION_KEY": "maycon",
put a real key here

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/internal/subscription/subscription.go
> +	subsQuery := main.db.Raw(FindOneQuery(subscriptionId.String())).Row()
Verify if this is injection safe, the query is built using string placeholders with

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/internal/subscription/queries.go
> +	AND deleted_at IS NULL`, configuration.GetConfiguration("ENCRYPTION_KEY"), subscriptionId)
is this placeholder substitution injection safe?

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/internal/configuration/configuration.go
> +	"ENCRYPTION_KEY": "maycon",
What about use only the .env file and when the variable is not found we could throw an error, or at startup check if all variables have values

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/web/api/middleware.go
> +		fmt.Println(r.RequestURI)
what the purpose of this print call?

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/web/api/serverapi.go
> +
i think it's a good ideia we have a readiness api too, with the check if the database and the queue are both up

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/web/api/subscription/subscription.go
> +	util2 "hermes/web/util"
why its util2? there no other util import here, if it's necessary, why not call it restUtil?

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/web/util/error.go
> +	errors.SimpleError
i'm worried about returning some internal error specificity in this, maybe we can generalize the returns to return a generic message or could return a specific one but with no technical information in it, like database information

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/web/api/subscription/subscription.go
> +			util2.NewResponse(w, http.StatusInternalServerError, err)
the error stuff problems

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/web/api/subscription/subscription.go
> +			util2.NewResponse(w, http.StatusInternalServerError, err)
the error stuff problems

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/web/api/subscription/subscription.go
> +			util2.NewResponse(w, http.StatusInternalServerError, err)
the error stuff problems

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/internal/messageexecutionhistory/main.go
> +}
No unit tests

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/internal/message/main.go
> +}
No unit tests

2021-01-19 17:52 UTC, arthurpuccizup commented on hermes/internal/subscription/main.go
> +}
No unit tests

2021-01-20 13:28 UTC, gabrielleitezup commented on hermes/go.mod
> +go 1.14
Go version updated

2021-01-20 13:46 UTC, gabrielleitezup commented on hermes/internal/subscription/queries.go
> +	AND deleted_at IS NULL`, configuration.GetConfiguration("ENCRYPTION_KEY"), subscriptionId)
Now it is. (Query removed :D)

2021-01-20 17:57 UTC, gabrielleitezup commented on hermes/internal/subscription/subscription.go
> +	subsQuery := main.db.Raw(FindOneQuery(subscriptionId.String())).Row()
Solved

2021-01-20 18:57 UTC, gabrielleitezup commented on hermes/web/api/middleware.go
> +		fmt.Println(r.RequestURI)
removed

2021-01-20 18:58 UTC, gabrielleitezup commented on hermes/internal/configuration/configuration.go
> +	"ENCRYPTION_KEY": "maycon",
done

2021-01-20 18:58 UTC, gabrielleitezup commented on hermes/internal/configuration/configuration.go
> +	"ENCRYPTION_KEY": "maycon",
Done (with sadness..)

2021-01-26 18:13 UTC, gabrielleitezup commented on hermes/web/api/serverapi.go
> +
Done

2021-01-26 18:14 UTC, gabrielleitezup commented on hermes/web/api/subscription/subscription.go
> +	util2 "hermes/web/util"
Done

2021-01-26 18:14 UTC, gabrielleitezup commented on hermes/web/util/error.go
> +	errors.SimpleError
Will be fixed in a future PR.

2021-01-26 18:14 UTC, gabrielleitezup commented on hermes/web/api/subscription/subscription.go
> +			util2.NewResponse(w, http.StatusInternalServerError, err)
Will be fixed in a future PR.

2021-01-26 18:14 UTC, gabrielleitezup commented on hermes/web/api/subscription/subscription.go
> +			util2.NewResponse(w, http.StatusInternalServerError, err)
Will be fixed in a future PR.

2021-01-26 18:15 UTC, gabrielleitezup commented on hermes/web/api/subscription/subscription.go
> +			util2.NewResponse(w, http.StatusInternalServerError, err)
Will be fixed in a future PR.

2021-01-26 18:15 UTC, gabrielleitezup commented on hermes/web/api/subscription/subscription.go
> +			util2.NewResponse(w, http.StatusInternalServerError, err)
Will be fixed in a future PR.

2021-01-26 18:15 UTC, gabrielleitezup commented on hermes/internal/messageexecutionhistory/main.go
> +}
Will be fixed in a future PR.

2021-01-26 18:15 UTC, gabrielleitezup commented on hermes/internal/message/main.go
> +}
Will be fixed in a future PR.

2021-01-26 18:15 UTC, gabrielleitezup commented on hermes/internal/subscription/main.go
> +}
Will be fixed in a future PR.

2021-01-26 20:23 UTC, closed without merging