Added new validation in the createModuleRequest
ZupIT/charlescd pull request #779
Opened 2021-01-07 20:58 UTC by lucassaleszup

Signed-off-by: Lucas Sales <lucas.sales@zup.com.br>

2021-01-08 17:02 UTC, leandrorodrigueszup commented on butler/src/app/v2/api/deployments/dto/create-module-request.dto.ts
> +  @Validate(ComponentIsNotNull, { })
Is it really necessary a new `ValidateConstraint`? `IsNotEmpty` doesn't work?

2021-01-11 13:38 UTC, lucassaleszup commented on butler/src/app/v2/api/deployments/dto/create-module-request.dto.ts
> +  @Validate(ComponentIsNotNull, { })
No, if you use @Validate (), it will always do the evaluations, it always gave an error (500, internal server error) due to validations waiting for non-empty components.
Another approach is to make all validations null-safe.

2021-01-11 13:52 UTC, leandrorodrigueszup commented on butler/src/app/v2/api/deployments/dto/create-module-request.dto.ts
> +  @Validate(ComponentIsNotNull, { })
ok

2021-01-11 13:52 UTC, leandrorodrigueszup approved these changes

2021-02-08 19:35 UTC, thallesfreitaszup submitted a review, later dismissed

2021-02-09 13:13 UTC, lucasbfernandes requested changes

2021-02-09 13:13 UTC, lucasbfernandes commented on butler/src/app/v2/api/deployments/validations/component-not-empty.ts
> +      throw new HttpException({ error: 'Bad Request', message:['components could not be null or empty'], statusCode: HttpStatus.BAD_REQUEST  }, HttpStatus.BAD_REQUEST)
Change to "components *should* not be null or empty"

2021-02-11 18:26 UTC, lucasbfernandes approved these changes

2021-02-11 18:26 UTC, thallesfreitaszup approved these changes

2021-02-11 18:37 UTC, lucasbfernandes approved these changes

2021-02-11 18:42 UTC, thallesfreitaszup approved these changes

2021-02-19 16:21 UTC, merged