Datasource improvements
ZupIT/charlescd pull request #783
Opened 2021-01-08 17:05 UTC by lucassaleszup

2021-01-08 17:08 UTC, bCatanant approved these changes

2021-01-08 17:19 UTC, ifdouglas submitted a review, later dismissed

2021-01-11 13:38 UTC, bCatanant approved these changes

2021-01-11 13:39 UTC, ifdouglas requested changes

2021-01-11 13:39 UTC, ifdouglas commented on ui/src/modules/Settings/Credentials/Sections/MetricProvider/styled.ts
> +  }
What do you think put this together?

```suggestion
  i {
    width: 35px;
    height: 20px;
    
    ::after {
      width: 14px;
      height: 14px;
    }
    
    ::before {
      width: 31px;
      height: 16px;
    }
  }
```

2021-01-11 14:11 UTC, ifdouglas approved these changes

2021-01-11 14:13 UTC, bCatanant approved these changes

2021-01-12 14:27 UTC, merged