Feature registry connection (Azure, dockerhub, GCP, Harbor and AWS)
ZupIT/charlescd pull request #788
Opened 2021-01-11 18:34 UTC by lucassaleszup

Change branch name because of hypotheses board.

2021-01-11 18:40 UTC, monicaribeiro submitted a review, later dismissed

2021-01-11 18:45 UTC, pedroborgeszup submitted a review, later dismissed

2021-01-14 17:57 UTC, monicaribeiro approved these changes

2021-01-14 18:00 UTC, ifdouglas requested changes

2021-01-14 18:06 UTC, ifdouglas approved these changes

2021-01-14 18:23 UTC, bCatanant commented on ui/src/modules/Settings/Credentials/Sections/Registry/__tests__/SectionRegistry.spec.tsx
>    waitFor(() => expect(cancelIcon).not.toBeInTheDocument());
Always try to use **await** before **waitFor**

2021-01-14 18:32 UTC, bCatanant approved these changes

2021-01-14 18:35 UTC, ifdouglas approved these changes

2021-01-14 18:45 UTC, merged