Moove webhook crud apis
ZupIT/charlescd pull request #801
Opened 2021-01-14 18:28 UTC by barbararochazup

**What is:** 
Expose CRUD APIs from webhook feature in moove and integration with Hermes APIS

- POST /v1/webhooks

- GET /v1/webhooks/{id}

- PATCH /v1/webhooks/{id}

- DELETE /v1/webhooks/{id}

**Signed-off-by:** barbararochazup <barbara.rocha@zup.com.br>

2021-01-14 18:30 UTC, pedroborgeszup approved these changes

2021-01-14 20:49 UTC, arthurpuccizup requested changes
Fiquei com uma dúvida também, no caso a gente não tem um list para as subscriptions do Hermes, como vamos conseguir esses ids para as operações de UPDATE, DELETE e GET

2021-01-14 20:49 UTC, arthurpuccizup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/webhook/request/CreateWebhookSubscriptionRequest.kt
> +    val description: String,
será que não rola fazer uma validação da quantidade máxima / mínima de caracteres que tem quer?

2021-01-14 20:49 UTC, arthurpuccizup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/webhook/request/CreateWebhookSubscriptionRequest.kt
> +    val url: String,
tem um outro PR que recebe url request que faz validação para um url válida, foi até um dos quesitos de segurança que o pessoal levantou, será que não rola fazer aqui também? o PR se não me falha a memória é o 796

2021-01-15 13:05 UTC, arthurpuccizup approved these changes

2021-01-15 13:23 UTC, merged