Registry improvements
ZupIT/charlescd pull request #812
Opened 2021-01-18 17:57 UTC by lucassaleszup

Signed-off-by: Lucas Sales <lucas.sales@zup.com.br>

2021-01-18 18:37 UTC, bCatanant approved these changes

2021-01-18 18:41 UTC, ifdouglas requested changes

2021-01-18 18:41 UTC, ifdouglas commented on ui/src/core/components/Form/Select/Single/SingleValue.tsx
> +  <Styled.StyledSingleValue {...props}>
```suggestion
  <Styled.Single {...props}>
```
or
```suggestion
  <Styled.SingleValue {...props}>
```

2021-01-18 18:41 UTC, ifdouglas commented on ui/src/modules/Settings/Credentials/Sections/Registry/Form.tsx
> +    }
```suggestion
setShowPlaceholder(['https://', 'http://'].includes(addressListener));
```

2021-01-18 18:41 UTC, ifdouglas commented on ui/src/modules/Settings/Credentials/Sections/Registry/styled.ts
> +const StyledInputPlaceholder = styled(TextComponent.h4)`
```suggestion
const Placeholder = styled(TextComponent.h4)`
```

2021-01-18 18:41 UTC, ifdouglas commented on ui/src/modules/Settings/Credentials/Sections/Registry/styled.ts
> +  StyledInputPlaceholder
```suggestion
  Placeholder
```

2021-01-18 18:41 UTC, ifdouglas commented on ui/src/modules/Settings/Credentials/Sections/Registry/Form.tsx
> +  const returnRegistryIcon = () => {
We usually have been using the prefix `render` or `get` to return a component

```suggestion
  const renderRegistryIcon = () => {
```

2021-01-18 18:41 UTC, ifdouglas commented on ui/src/modules/Settings/Credentials/Sections/Registry/Form.tsx
> +                  }
`import endsWith from 'lodash/endsWith'`

```suggestion
   return (!endsWith(value, 'https://') && !endsWith(value, 'http://')) || !isEmpty(value);
```

I made this in my mind, so maybe the condition won't fit the problem.

2021-01-19 13:58 UTC, lucassaleszup commented on ui/src/modules/Settings/Credentials/Sections/Registry/Form.tsx
> +                  }
this condition does not check whether the string contains https:// or http://.
we need to check: 
1st if string is just https or http.
2nd if the string contains https or http and more text
3rd if the string exists, but does not contain https or http, returns false

2021-01-19 14:37 UTC, bCatanant approved these changes

2021-01-19 14:37 UTC, ifdouglas approved these changes

2021-01-19 18:34 UTC, closed without merging