Butler operator routes
ZupIT/charlescd pull request #820
Opened 2021-01-20 18:03 UTC by leandrorodrigueszup

Create hook to return istio routes manifests

2021-01-21 18:13 UTC, thallesfreitaszup requested changes

2021-01-21 18:13 UTC, thallesfreitaszup commented on butler/src/app/v2/operator/use-cases/create-routes-manifests.usecase.ts
> +      const activeComponents = await this.componentsRepository.findActiveComponents('b46fd548-0082-4021-ba80-a50703c44a3a')
why the parameter it's hard-coded?

2021-01-21 18:32 UTC, leandrorodrigueszup commented on butler/src/app/v2/operator/use-cases/create-routes-manifests.usecase.ts
> +      const activeComponents = await this.componentsRepository.findActiveComponents('b46fd548-0082-4021-ba80-a50703c44a3a')
That was a mistake. Fixed!

2021-01-21 18:37 UTC, thallesfreitaszup approved these changes

2021-01-27 17:23 UTC, cpgo approved these changes

2021-01-27 17:23 UTC, merged