Hermes workflows
ZupIT/charlescd pull request #822
Opened 2021-01-20 18:59 UTC by pedroborgeszup

2021-01-20 19:39 UTC, arthurpuccizup requested changes

2021-01-20 19:39 UTC, arthurpuccizup commented on hermes/Dockerfile
> +FROM golang:1.14-alpine as builder
```suggestion
FROM golang:1.15-alpine as builder
```

As if it's already building with version 1.15, use the image with the same version

2021-01-20 19:39 UTC, arthurpuccizup commented on hermes/Makefile
> +				$(GOTEST) ./...
I think that it's not necessary both of these commands, maybe in a future version we could have, but for now is unnecessary, since is the same command with different names

2021-01-20 19:39 UTC, arthurpuccizup commented on hermes/Makefile
> +GOBUILDPLUGIN=$(GOCMD) build -buildmode=plugin
This is not necessary, since Hermes does not use any plugin, and doesn't need any build plugin build call

2021-01-20 19:50 UTC, arthurpuccizup approved these changes

2021-01-21 14:11 UTC, barbararochazup approved these changes

2021-01-21 14:19 UTC, merged