Users: Pagination and infinite scroll
ZupIT/charlescd pull request #824
Opened 2021-01-21 17:36 UTC by luanecavalcantizup

## Frontend

- Include infinite scroll to users

## Backend

2021-02-09 14:42 UTC, monicaribeiro approved these changes

2021-02-09 14:43 UTC, ifdouglas requested changes

2021-02-09 19:08 UTC, luanecavalcantizup commented on ui/src/modules/Groups/__tests__/hooks.spec.ts
> +import { waitFor } from 'unit-test/testUtils';
No, it is not. I changed it while was looking through the test files. But actually, what was the conclusion about that discussion on "the boy scout rule"? because I think we didn't arrived in a conclusion (correct me if I am not right please :)

2021-02-09 19:53 UTC, ifdouglas commented on ui/src/modules/Groups/__tests__/hooks.spec.ts
> +import { waitFor } from 'unit-test/testUtils';
I thought the conclusion was open PR based on their goals. But we can discuss this on the next FrontEnd chapter.

2021-02-11 14:59 UTC, monicaribeiro approved these changes

2021-02-11 15:01 UTC, ifdouglas approved these changes

2021-02-18 13:59 UTC, merged