Moove webhook publish events
ZupIT/charlescd pull request #830
Opened 2021-01-26 20:59 UTC by barbararochazup

Notify Hermes module when:
Deploy started and finished (with success or not)
Undeploy started and finished (with success or not)

2021-01-28 18:50 UTC, emiteze requested changes

2021-01-28 18:50 UTC, emiteze commented on moove/application/src/main/kotlin/io/charlescd/moove/application/WebhookEventService.kt
> +    }
Use find from our BuildService would remove the need of this code

2021-01-28 18:50 UTC, emiteze commented on moove/application/src/main/kotlin/io/charlescd/moove/application/deployment/request/DeploymentCallbackRequest.kt
> +    fun isUndeployEvent() = listOf(DeploymentRequestStatus.UNDEPLOYED, DeploymentRequestStatus.UNDEPLOYED).contains(this.deploymentStatus)
Duplicated DeploymentRequestStatus.UNDEPLOYED

2021-01-28 18:50 UTC, emiteze commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/service/client/HermesPublisherClient.kt
> +@FeignClient(name = "hermesClient", url = "\${charlescd.hermes.url}", configuration = [ HermesPublisherEncoderConfiguration::class])
Can we remove this blank space inside of this configuration list?

2021-01-28 19:01 UTC, pedroborgeszup approved these changes

2021-01-29 13:40 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/deployment/request/DeploymentCallbackRequest.kt
> +    fun isUndeployEvent() = listOf(DeploymentRequestStatus.UNDEPLOYED, DeploymentRequestStatus.UNDEPLOYED).contains(this.deploymentStatus)
This method was not called, so I removed them

2021-01-29 13:40 UTC, barbararochazup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/service/client/HermesPublisherClient.kt
> +@FeignClient(name = "hermesClient", url = "\${charlescd.hermes.url}", configuration = [ HermesPublisherEncoderConfiguration::class])
Done

2021-01-29 13:47 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/WebhookEventService.kt
> +    }
Done

2021-01-29 14:18 UTC, emiteze approved these changes

2021-01-29 14:35 UTC, merged