Improve error details
ZupIT/charlescd pull request #832
Opened 2021-01-27 13:30 UTC by thallesfreitaszup

2021-02-09 13:18 UTC, cpgo approved these changes

2021-02-09 13:20 UTC, lucasbfernandes requested changes

2021-02-09 13:20 UTC, lucasbfernandes commented on circle-matcher/src/main/java/io/charlescd/circlematcher/handler/ExceptionUtils.java
> +package io.charlescd.circlematcher.handler;
Insert license header

2021-02-09 13:20 UTC, lucasbfernandes commented on circle-matcher/src/test/groovy/io/charlescd/circlematcher/handler/DefaultErrorResponseTest.groovy
> +package io.charlescd.circlematcher.handler
Insert license header

2021-02-09 13:20 UTC, lucasbfernandes commented on circle-matcher/src/test/groovy/io/charlescd/circlematcher/handler/ErrorHandlerTest.groovy
>  package io.charlescd.circlematcher.handler
Insert license header

2021-02-09 13:20 UTC, lucasbfernandes commented on moove/api/src/main/kotlin/io/charlescd/moove/api/MooveExceptionHandler.kt
License header

2021-02-09 13:56 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/handler/ExceptionUtils.java
> +package io.charlescd.circlematcher.handler;
done

2021-02-09 13:56 UTC, thallesfreitaszup commented on circle-matcher/src/test/groovy/io/charlescd/circlematcher/handler/DefaultErrorResponseTest.groovy
> +package io.charlescd.circlematcher.handler
done

2021-02-09 13:57 UTC, thallesfreitaszup commented on circle-matcher/src/test/groovy/io/charlescd/circlematcher/handler/ErrorHandlerTest.groovy
>  package io.charlescd.circlematcher.handler
done

2021-02-09 13:57 UTC, thallesfreitaszup commented on moove/api/src/main/kotlin/io/charlescd/moove/api/MooveExceptionHandler.kt
this file has license

2021-02-09 15:09 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/handler/ExceptionUtils.java
> +    public static DefaultErrorResponse createNotFoundErrorResponse(String message, String sourceString) {
This method could be replaced by something like (the same for `createBadRequestError` and `createInternalServerError`:

`
public static DefaultErrorResponse createNotFoundErrorResponse(String message, String sourceString) {
     return createBusinessExceptionError(message, "Not found", sourceString, 404); 
}
`

2021-02-09 15:15 UTC, eliasalveszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/handler/ExceptionUtils.java
> +            Exception exception) {
`exception` parameter is not used

2021-02-09 19:35 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/handler/ExceptionUtils.java
> +    public static DefaultErrorResponse createNotFoundErrorResponse(String message, String sourceString) {
done

2021-02-09 19:35 UTC, thallesfreitaszup commented on circle-matcher/src/main/java/io/charlescd/circlematcher/handler/ExceptionUtils.java
> +            Exception exception) {
removed.Thanks!

2021-02-12 13:57 UTC, eliasalveszup approved these changes

2021-02-23 13:34 UTC, cpgo submitted a review, later dismissed

2021-02-24 17:48 UTC, eliasalveszup approved these changes

2021-02-24 17:50 UTC, lucasbfernandes approved these changes

2021-02-25 17:19 UTC, merged