Hermes charts
ZupIT/charlescd pull request #836
Opened 2021-01-28 13:36 UTC by pedroborgeszup

2021-01-28 18:49 UTC, barbararochazup commented on install/helm-chart/templates/charlescd-hermes-secret.yaml
> +{{- if .Values.compass.enabled }}
Values.compass.enabled tá correto?

2021-01-28 18:51 UTC, barbararochazup commented on install/helm-chart/charts/rabbitmq/values.schema.json
> +          "type": "boolean",
essa parte do prometheus foi adicionada? ou ja existia?

2021-01-28 18:53 UTC, barbararochazup reviewed
algumas duvidas, somente

2021-01-28 18:56 UTC, pedroborgeszup commented on install/helm-chart/templates/charlescd-hermes-secret.yaml
> +{{- if .Values.compass.enabled }}
Ctrl + C and Ctrl + V problems, sorry! hahah

2021-01-28 18:59 UTC, pedroborgeszup commented on install/helm-chart/charts/rabbitmq/values.schema.json
> +          "type": "boolean",
These files from RabbitMQ come like this by default after unzipping the .tgz.

2021-01-29 14:38 UTC, pedroborgeszup commented on install/helm-chart/charts/rabbitmq/values.schema.json
> +          "type": "boolean",
This files wasn't necessary.

2021-01-29 17:38 UTC, lucassaleszup requested changes

2021-01-29 17:38 UTC, lucassaleszup commented on install/helm-chart/requirements.yaml
> +  version: "3.8.11"
add a condition rabbitmq.enabled

2021-01-29 17:38 UTC, lucassaleszup commented on install/helm-chart/requirements.yaml
> +  version: "3.8.11"
and the repository

2021-01-29 17:48 UTC, lucassaleszup approved these changes

2021-01-29 17:48 UTC, pedroborgeszup commented on install/helm-chart/requirements.yaml
> +  version: "3.8.11"
Done

2021-01-29 18:34 UTC, barbararochazup approved these changes

2021-02-01 18:15 UTC, celiofilhozup approved these changes

2021-02-01 18:33 UTC, merged