Moove webhook not found error event
ZupIT/charlescd pull request #852
Opened 2021-01-29 18:37 UTC by barbararochazup

2021-02-03 15:02 UTC, emiteze approved these changes

2021-02-05 20:12 UTC, monicaribeiro requested changes

2021-02-05 20:12 UTC, monicaribeiro commented on moove/application/src/main/kotlin/io/charlescd/moove/application/deployment/impl/CreateDeploymentInteractorImpl.kt
> +    private fun notifyEvent(status: WebhookEventStatusEnum, deployment: Deployment, error: String? = null) {
Esse mesmo trecho de código está replicado no  UndeployInteractor, será que podemos bolar uma forma de melhorar?

2021-02-17 15:16 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/deployment/impl/CreateDeploymentInteractorImpl.kt
> +    private fun notifyEvent(status: WebhookEventStatusEnum, deployment: Deployment, error: String? = null) {
Refactor realizado.

2021-02-17 15:17 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/deployment/impl/UndeployInteractorImpl.kt
> +    private fun getDeployment(deploymentId: String, workspaceId: String): Deployment {
Eu preciso mandar uma notificação qdo ocorre o erro de não encontrar a entidade. Por isso criei o método na interactor. Mas eu utilizo o método da própria service aqui.

2021-02-17 15:17 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/deployment/impl/CreateDeploymentInteractorImpl.kt
> +    private fun getBuild(buildId: String, workspaceId: String): Build {
Eu preciso mandar uma notificação de evento qdo ocorre o erro de não encontrar a entidade. Por isso criei o método na interactor. Mas eu utilizo o método da própria service aqui.

2021-02-18 14:21 UTC, monicaribeiro approved these changes

2021-02-18 14:22 UTC, merged