Adding initial structure for new ext auth server (gate)
ZupIT/charlescd pull request #898
Opened 2021-02-09 20:47 UTC by emiteze

Signed-off-by: Mateus Cruz <emiteze@hotmail.com>

2021-02-10 12:24 UTC, barbararochazup approved these changes

2021-02-10 12:24 UTC, barbararochazup commented on gate/cmd/db.go
> +		configuration.Get("DB_HOST"),
Only suggestion to more clean view 

db, err := gorm.Open(postgres.Open(fmt.Sprintf("host=%s port=%s user=%s dbname=%s password=%s sslmode=%s",
		GetConfiguration("DB_HOST"),
		GetConfiguration("DB_PORT"),
		GetConfiguration("DB_USER"),
		GetConfiguration("DB_NAME"),
		GetConfiguration("DB_PASSWORD"),
		GetConfiguration("DB_SSL"),
	)), &gorm.Config{})

2021-02-10 12:24 UTC, barbararochazup commented on gate/cmd/http.go
> +	api := s.echo.Group("")
By default we are using gorilla/mux to request routing and dispatcher. 
Maybe it would be interesting to use it.

https://github.com/gorilla/mux

2021-02-11 14:22 UTC, monicaribeiro requested changes

2021-02-11 14:22 UTC, monicaribeiro commented on gate/cmd/http.go
> +func (cb customBinder) Bind(i interface{}, c echo.Context) (err error) {
Maybe we could write a descriptive name for the variable 'i'.

2021-02-11 14:22 UTC, monicaribeiro commented on gate/cmd/http.go
> +func (cv *CustomValidator) Validate(i interface{}) error {
Maybe we could write a descriptive name for the variable 'cv'.

2021-02-11 14:22 UTC, monicaribeiro commented on gate/cmd/http.go
> +func (cv *CustomValidator) Validate(i interface{}) error {
Maybe we could write a descriptive name for the variable 'i'.

2021-02-11 14:22 UTC, monicaribeiro commented on gate/cmd/http.go
> +	v := validator.New()
Maybe we could write a descriptive name for the variable 'v'.

2021-02-18 14:23 UTC, monicaribeiro approved these changes

2021-02-18 15:06 UTC, merged