[UserGroups] Prevent duplicate list after updates
ZupIT/charlescd pull request #918
Opened 2021-02-19 12:03 UTC by ifdouglas

2021-02-19 17:07 UTC, bCatanant submitted a review, later dismissed

2021-02-19 17:36 UTC, washingtonsoares submitted a review, later dismissed

2021-02-26 16:24 UTC, bCatanant submitted a review, later dismissed

2021-03-01 13:25 UTC, Leandroqo requested changes

2021-03-01 13:25 UTC, Leandroqo commented on ui/src/modules/Groups/Tabs/Form/__tests__/Form.spec.tsx
> +  act(() => {
https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning

2021-03-01 17:58 UTC, ifdouglas commented on ui/src/modules/Groups/Tabs/Form/__tests__/Form.spec.tsx
> +  act(() => {
Interesting, but I realize that this issue (in this specific form) was happening because we were using `onChange` mode on `react-hook-form` and we didn't need this here, so I changed to `onBlur` mode and removed the `act`s from this tests.

2021-03-01 19:22 UTC, Leandroqo approved these changes

2021-03-03 13:55 UTC, bCatanant approved these changes

2021-03-09 18:46 UTC, merged