Hermes - rabbit consumer
ZupIT/charlescd pull request #920
Opened 2021-02-19 13:04 UTC by pedroborgeszup

2021-02-22 17:37 UTC, monicaribeiro requested changes

2021-02-22 17:37 UTC, monicaribeiro commented on hermes/internal/notification/message/main.go
> +	"hermes/rabbitClient"
```suggestion
	"hermes/rabbitclient"
```

Should it be cammel case?

2021-02-22 17:37 UTC, monicaribeiro commented on hermes/internal/notification/payloads/messagepayloads.go
> +	ExternalId uuid.UUID       `json:"externalId"` //workspace-id
```suggestion
	ExternalId uuid.UUID       `json:"externalId"`
```

Suggestion: avoid comments

2021-02-22 17:37 UTC, monicaribeiro commented on hermes/internal/subscription/subscription.go
> +func (main Main) SendWebhookEvent(msg payloads.MessageResponse) errors.Error {
Is there any problem if we split this function in other small ones? I guess it would be more readable.

2021-02-22 19:29 UTC, pedroborgeszup commented on hermes/internal/subscription/subscription.go
> +func (main Main) SendWebhookEvent(msg payloads.MessageResponse) errors.Error {
this function basically creates the request and transforms the objects that we will need in it, I don't see why splitting it

2021-02-22 21:42 UTC, emiteze requested changes

2021-02-22 21:42 UTC, emiteze commented on hermes/rabbitclient/rabbitclient.go
> +package rabbitclient
Missing license

2021-02-22 21:42 UTC, emiteze commented on hermes/internal/notification/messagePubSub/main.go
> +package messagePubSub
Missing license

2021-02-22 21:42 UTC, emiteze commented on hermes/internal/notification/messagePubSub/consumer.go
> +package messagePubSub
Missing license

2021-02-22 22:10 UTC, barbararochazup commented on hermes/rabbitclient/rabbitclient.go
> +package rabbitclient
Done

2021-02-22 22:10 UTC, barbararochazup commented on hermes/internal/notification/messagePubSub/main.go
> +package messagePubSub
Done

2021-02-22 22:11 UTC, barbararochazup commented on hermes/internal/notification/messagePubSub/consumer.go
> +package messagePubSub
Done

2021-02-23 13:37 UTC, emiteze approved these changes

2021-02-23 13:45 UTC, monicaribeiro approved these changes

2021-02-23 13:45 UTC, merged