Butler executions filters
ZupIT/charlescd pull request #922
Opened 2021-02-19 13:50 UTC by leandrorodrigueszup

2021-02-23 13:35 UTC, cpgo approved these changes

2021-02-23 13:43 UTC, lucasbfernandes approved these changes

2021-03-01 19:52 UTC, cpgo commented on butler/src/app/v2/api/deployments/dto/execution/paginated-execution-query.dto.ts
> -  @IsBooleanString()
Why remove the `IsBooleanString` validation? Is it not needed?

2021-03-01 19:53 UTC, leandrorodrigueszup commented on butler/src/app/v2/api/deployments/dto/execution/paginated-execution-query.dto.ts
> -  @IsBooleanString()
Because its not mandatory anymore!

2021-03-01 19:59 UTC, lucasbfernandes requested changes

2021-03-01 19:59 UTC, lucasbfernandes commented on butler/src/app/v2/api/deployments/use-cases/paginated-executions.usecase.ts
> +  }
Wouldn't be better to put this in a utils file? I think we might reuse this elsewhere

2021-03-02 14:21 UTC, leandrorodrigueszup commented on butler/src/app/v2/api/deployments/dto/execution/paginated-execution-query.dto.ts
> -  @IsBooleanString()
Done

2021-03-02 14:22 UTC, leandrorodrigueszup commented on butler/src/app/v2/api/deployments/use-cases/paginated-executions.usecase.ts
> +  }
I usually try to avoid _util_ files. So, I changed the paginated response interface, so the _isLast_ method could in it.

2021-03-03 14:31 UTC, lucasbfernandes approved these changes

2021-03-04 13:00 UTC, cpgo approved these changes

2021-03-10 18:43 UTC, thallesfreitaszup approved these changes

2021-03-10 18:55 UTC, merged