Feature/get system token
ZupIT/charlescd pull request #939
Opened 2021-02-26 16:29 UTC by barbararochazup

## Issue Description

Implementation of Get system token endpoint

## API Information

### Request (if appropriate):
**URL:** GET /api/v1/system-token/{id}

### Response:
> Status: **200 OK**

Payload:
```json
{
  "id": "06666a99-7800-4c83-af2c-a1a1d5e1bb2e",
  "name": "Token Test",
  "permissions": [
    {
      "id": "12666a99-7800-4c83-af2c-a1a1d5e1bb3f",
      "name": "MAINTAINER"
    }
  ],
  "cretedAt": "2020-02-26 13:00:00",
  "author": "charlescd@email.com"
}
```

> Status: **404 NOT FOUND**

Payload:
```json
{
    "id": "5832ec91-88c9-4ca5-861e-af49e655048e",
    "message": "Not found token",
    "Type": "NotFoundError",
    "timestamp": "1614345707",
    "meta": null
}
```

> Status: **500 INTERNAL ERROR**

Payload:
```json
{
    "id": "5832ec91-88c9-4ca5-861e-af49e655048e",
    "message": "Internal error details",
    "Type": "InternaldError",
    "timestamp": "1614345707",
    "meta": null
}
```

> Status: **400 BAD REQUEST**

Payload:
```json
{
    "id": "9cebaea5-69e6-4865-b0ec-aefa0ceadc65",
    "message": "Parse id failed",
    "Type": "ParseError",
    "timestamp": "1614356891",
    "meta": null
}
```

2021-02-26 17:05 UTC, pedroborgeszup approved these changes

2021-02-26 17:37 UTC, barbararochazup commented on gate/internal/repository/system_token_repository.go
> +			return handlerError("Not found token", "unit.GetById.First", res.Error, logging.NotFoundError)
Done

2021-02-26 17:50 UTC, pedroborgeszup requested changes

2021-02-26 17:50 UTC, pedroborgeszup commented on gate/web/api/handlers/system_token_handler.go
> +		user, err := getSystemToken.Execute(uuid)
Shouldn't the getSystemToken result variable be `systemToken` instead of `user`?

2021-02-26 17:53 UTC, pedroborgeszup approved these changes

2021-02-26 17:53 UTC, barbararochazup commented on gate/web/api/handlers/system_token_handler.go
> +		user, err := getSystemToken.Execute(uuid)
Done

2021-03-01 14:08 UTC, monicaribeiro requested changes

2021-03-01 14:08 UTC, monicaribeiro commented on gate/tests/unit/system_token_test.go
> +
Remove extra lines.

2021-03-01 17:15 UTC, barbararochazup commented on gate/tests/unit/system_token_test.go
> +
Done

2021-03-03 13:32 UTC, monicaribeiro requested changes

2021-03-03 13:32 UTC, monicaribeiro commented on gate/tests/unit/system_token_test.go
> +	st.systemTokenRepository.On("FindById", mock.Anything).Return(domain.SystemToken{ID: uuid.New()}, nil)
Suggestion:

To make sure that the correct input is going to be received, you could initialize a system token and reference it here:
```suggestion
	st.systemTokenRepository.On("FindById", systemToken.ID).Return(systemToken, nil)
```

2021-03-03 13:32 UTC, monicaribeiro commented on gate/tests/unit/system_token_test.go
> +	require.Nil(st.T(), err)
You could add another verification to make sure that the correct id was passed to the FindById method. Also, check if FindById was called once.

2021-03-03 13:32 UTC, monicaribeiro commented on gate/tests/unit/system_token_test.go
> +	st.systemTokenRepository.On("FindById", mock.Anything).Return(domain.SystemToken{}, logging.NewError("Not found error", logging.CustomError{} ,  logging.NotFoundError, nil))
Tha same comments I made before are applicable here.

2021-03-03 13:32 UTC, monicaribeiro commented on gate/tests/unit/system_token_test.go
> +	st.systemTokenRepository.On("FindById", mock.Anything).Return(domain.SystemToken{}, logging.NewError("Not found error", logging.CustomError{} ,  logging.NotFoundError, nil))
the**

2021-03-03 13:32 UTC, monicaribeiro commented on gate/tests/unit/system_token_test.go
> +	st.systemTokenRepository.On("FindById", mock.Anything).Return(domain.SystemToken{}, logging.NewError("Internal error", logging.CustomError{}, logging.InternalError, nil))
The same comments I made before are applicable here.

2021-03-03 14:20 UTC, barbararochazup commented on gate/tests/unit/system_token_test.go
> +	st.systemTokenRepository.On("FindById", mock.Anything).Return(domain.SystemToken{}, logging.NewError("Internal error", logging.CustomError{}, logging.InternalError, nil))
Done

2021-03-03 14:20 UTC, barbararochazup commented on gate/tests/unit/system_token_test.go
> +	st.systemTokenRepository.On("FindById", mock.Anything).Return(domain.SystemToken{}, logging.NewError("Not found error", logging.CustomError{} ,  logging.NotFoundError, nil))
Done

2021-03-03 14:20 UTC, barbararochazup commented on gate/tests/unit/system_token_test.go
> +	require.Nil(st.T(), err)
Done

2021-03-03 20:22 UTC, pedroborgeszup requested changes

2021-03-03 21:00 UTC, pedroborgeszup requested changes

2021-03-03 21:00 UTC, pedroborgeszup commented on gate/tests/unit/system_token_test.go
> +	require.Equal(st.T(), result.ID, uuid.Nil)
in an actual call, if an error occurs, the result object is returned empty, different from what is happening in the test

2021-03-03 21:01 UTC, pedroborgeszup requested changes

2021-03-03 21:01 UTC, pedroborgeszup commented on gate/tests/unit/system_token/system_token_test.go
> +	require.Equal(st.T(), result.ID, uuid.Nil)
in an actual call, if an error occurs, the result object is returned empty, different from what is happening in the test

2021-03-03 21:01 UTC, pedroborgeszup commented on gate/tests/unit/system_token/system_token_test.go
> +	require.Equal(st.T(), result.ID, uuid.Nil)
in an actual call, if an error occurs, the result object is returned empty, different from what is happening in the test

2021-03-03 21:12 UTC, monicaribeiro approved these changes

2021-03-03 21:40 UTC, barbararochazup commented on gate/web/api/handlers/representation/system_token.go
> +	LastUsedAt 		*time.Time `json:"last_used_atm,omitempty"`
done

2021-03-04 12:57 UTC, pedroborgeszup approved these changes

2021-03-04 14:00 UTC, merged