Removing unused chart
ZupIT/charlescd pull request #940
Opened 2021-02-26 18:25 UTC by bCatanant

Removing unused chart on charles C.D.

2021-03-03 13:15 UTC, arthurpuccizup requested changes
Why not remove the property health in the datasource registration, if there is no more health, this flag is not necessary anymore

2021-03-03 13:19 UTC, maycommit submitted a review, later dismissed

2021-03-03 15:31 UTC, icaroafonsozup commented
> Why not remove the property health in the datasource registration, if there is no more health, this flag is not necessary anymore

Property and references removed as asked.

2021-03-03 17:58 UTC, ifdouglas approved these changes

2021-03-03 17:58 UTC, ifdouglas commented on ui/src/modules/Circles/Menu/index.tsx
> +          <Styled.Icon name="circle-matcher" color="dark" size="15px" title={'circle matcher'} />
```suggestion
          <Styled.Icon name="circle-matcher" color="dark" size="15px" title="circle matcher" />
```

2021-03-03 18:12 UTC, ifdouglas submitted a review, later dismissed

2021-03-03 18:22 UTC, arthurpuccizup requested changes

2021-03-03 18:22 UTC, arthurpuccizup commented on compass/internal/tests/datasource_test.go
> + *  You may obtain a copy of the License atFindAllByWorkspace
Miss typing in the license

2021-03-03 18:22 UTC, arthurpuccizup commented on compass/migrations/20210303120000_alter_data_sources_table.down.sql
> +ALTER TABLE data_sources DROP COLUMN HEALTH;
This is not the "down" script, this is the "up" script, which by the way is missing

2021-03-03 20:30 UTC, icaroafonsozup commented on compass/internal/tests/datasource_test.go
> + *  You may obtain a copy of the License atFindAllByWorkspace
Resolved as asked.

2021-03-03 20:30 UTC, icaroafonsozup commented on compass/migrations/20210303120000_alter_data_sources_table.down.sql
> +ALTER TABLE data_sources DROP COLUMN HEALTH;
Resolved as asked.

2021-03-04 12:34 UTC, arthurpuccizup approved these changes

2021-03-04 12:36 UTC, ifdouglas approved these changes

2021-03-04 18:08 UTC, merged