Fix inconsistently displaying the menu after go to root path
ZupIT/charlescd pull request #942
Opened 2021-02-26 19:57 UTC by luanecavalcantizup

Signed-off-by: luanecavalcantizup <luane.cavalcanti@zup.com.br>

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

## Results

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

### Request (if appropriate):
> Url: **POST** {{url}}/hello/{{hello-code}}

Payload:
```json
{
    "key" : "value"
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "key" :  "value"
}
```
### Screenshots (if appropriate):

2021-03-02 13:55 UTC, ifdouglas submitted a review, later dismissed

2021-03-02 17:10 UTC, Leandroqo approved these changes

2021-03-15 14:20 UTC, ifdouglas requested changes

2021-03-15 19:20 UTC, luanecavalcantizup commented on ui/src/modules/Main/constants.ts
> +}[];
Hi @ifdouglas, please take a look at the last commit I did to meet with your sugestion of improvement. If there is a better way please tell me.

2021-03-15 19:22 UTC, ifdouglas approved these changes

2021-03-16 14:54 UTC, Leandroqo approved these changes

2021-03-17 13:22 UTC, Leandroqo approved these changes

2021-03-17 13:26 UTC, ifdouglas approved these changes

2021-03-19 13:15 UTC, merged