fix workspace response when hermes api throw error
ZupIT/charlescd pull request #947
Opened 2021-03-01 17:47 UTC by barbararochazup

Signed-off-by: barbararochazup <barbara.rocha@zup.com.br>

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

## Results

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

### Request (if appropriate):
> Url: **POST** {{url}}/hello/{{hello-code}}

Payload:
```json
{
    "key" : "value"
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "key" :  "value"
}
```
### Screenshots (if appropriate):

2021-03-03 13:21 UTC, monicaribeiro requested changes

2021-03-03 13:21 UTC, monicaribeiro commented on moove/application/src/main/kotlin/io/charlescd/moove/application/webhook/impl/CreateWebhookSubscriptionInteractorImpl.kt
> +        //return hermesService.subscribe(webhookService.getAuthorEmail(authorization), simpleWebhookSubscription)
I did not understand this change.

2021-03-03 13:21 UTC, monicaribeiro commented on moove/web/src/main/resources/application-local.properties
> +charlescd.hermes.url=https://charles-sandbox.continuousplatform.com/hermes
This should be a local URL.

2021-03-04 18:35 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/webhook/impl/CreateWebhookSubscriptionInteractorImpl.kt
> +        //return hermesService.subscribe(webhookService.getAuthorEmail(authorization), simpleWebhookSubscription)
It's only for tests. I removed them.

2021-03-04 18:35 UTC, barbararochazup commented on moove/web/src/main/resources/application-local.properties
> +charlescd.hermes.url=https://charles-sandbox.continuousplatform.com/hermes
It's only for tests. I removed them.

2021-03-05 14:25 UTC, emiteze approved these changes

2021-03-05 15:05 UTC, monicaribeiro approved these changes

2021-03-05 15:06 UTC, merged