Feature: revoke system token
ZupIT/charlescd pull request #951
Opened 2021-03-03 12:02 UTC by monicaribeiro

## Issue Description

Endpoint that revoke system token.

## Results

### Request (if appropriate):
> Url: **POST** {{url}}/api/v1/system-token/{{ID}}/revoke

### Response:
> Status: **204 NO CONTENT**

> Status: **404 NOT FOUND**

```
{
    "id": "9491aeb3-1e02-437d-8bdd-26fbe9c467af",
    "message": "Token not found",
    "detail": "record not found",
    "type": "NotFoundError",
    "timestamp": "1614772850",
    "_": null
}
```

> Status: **500 INTERNAL ERROR**

**Payload:**
```
{
    "id": "5832ec91-88c9-4ca5-861e-af49e655048e",
    "message": "Internal error details",
    "Type": "InternaldError",
    "timestamp": "1614345707",
    "meta": null
}
```

> Status: **400 BAD REQUEST**

**Payload:**

```
{
    "id": "9cebaea5-69e6-4865-b0ec-aefa0ceadc65",
    "message": "Parse id failed",
    "Type": "ParseError",
    "timestamp": "1614356891",
    "meta": null
}

```

2021-03-04 19:39 UTC, barbararochazup commented on gate/internal/repository/system_token_repository.go
> +		return handlerError("Update system token failed", "repository.Update.Updates", res.Error, "")
It's a **Internal Error** what should be returned to response service? Because when anyone error type was informed it's converted to Internal Error.

return handlerError("Update system token failed", "repository.Update.Updates", res.Error, **""**)

2021-03-05 17:59 UTC, barbararochazup approved these changes

2021-03-05 18:25 UTC, pedromcborges requested changes

2021-03-05 18:25 UTC, pedromcborges commented on gate/internal/use_case/system_token/revoke_system_token.go
> +	if !systemToken.Revoked {
we could return an error if this condition isn't true, what do you think?
Ex. "Token is alrealdy inactive" or "Token has already been revoked"

2021-03-05 18:57 UTC, monicaribeiro commented on gate/internal/use_case/system_token/revoke_system_token.go
> +	if !systemToken.Revoked {
A 422 code?

2021-03-05 19:37 UTC, emiteze requested changes

2021-03-05 19:37 UTC, emiteze commented on gate/internal/use_case/system_token/revoke_system_token.go
> +	if !systemToken.Revoked {
I agree with Pedro, we could return a 422 in this scenario

2021-03-05 19:40 UTC, pedromcborges commented on gate/internal/use_case/system_token/revoke_system_token.go
> +	if !systemToken.Revoked {
Agreed

2021-03-09 18:18 UTC, pedromcborges approved these changes

2021-03-09 19:17 UTC, emiteze approved these changes

2021-03-10 11:22 UTC, merged