Fix showing required field for an optional field when registering a module
ZupIT/charlescd pull request #953
Opened 2021-03-03 17:34 UTC by luanecavalcantizup

Signed-off-by: luanecavalcantizup <luane.cavalcanti@zup.com.br>

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

### Screenshots (if appropriate):

2021-03-04 17:04 UTC, ifdouglas requested changes
Removing the error prop will just mask the problem, I think this fields shouldn't be required.

2021-03-05 11:08 UTC, washingtonsoares approved these changes

2021-03-05 12:45 UTC, ifdouglas approved these changes

2021-03-05 12:46 UTC, washingtonsoares approved these changes

2021-03-10 19:39 UTC, bCatanant approved these changes

2021-03-16 20:32 UTC, monicaribeiro approved these changes

2021-03-16 20:33 UTC, merged