Remove cd configurations
ZupIT/charlescd pull request #957
Opened 2021-03-03 18:52 UTC by cpgo

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

## Results

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

### Request (if appropriate):
> Url: **POST** {{url}}/hello/{{hello-code}}

Payload:
```json
{
    "key" : "value"
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "key" :  "value"
}
```
### Screenshots (if appropriate):

2021-03-03 18:57 UTC, lucasbfernandes requested changes

2021-03-03 18:57 UTC, lucasbfernandes commented on butler/src/app/v2/api/deployments/dto/create-git-request.dto.ts
> +  public readonly gitToken: string
Change to `token`

2021-03-03 18:57 UTC, lucasbfernandes commented on butler/src/app/v2/api/deployments/dto/create-git-request.dto.ts
> +  public readonly gitProvider: GitProvidersEnum
Change to `provider`

2021-03-03 18:57 UTC, lucasbfernandes commented on butler/src/app/v2/operator/deployments.hook.controller.ts
> +    // const deployment = await this.deploymentRepository.findWithComponentsAndConfig(params.parent.spec.deploymentId)
Remove comment

2021-03-08 17:14 UTC, thallesfreitaszup approved these changes
Only questions

2021-03-08 17:14 UTC, thallesfreitaszup commented on butler/src/tests/v2/integration/use-cases/create-deployment-usecase.integration-spec.ts
> +-----END PGP MESSAGE-----
is this token a generated by moove? if not a think that would be a good test case if we could use a generic token generated by moove to ensure that the the encryption and decryption key are the same

2021-03-08 17:14 UTC, thallesfreitaszup commented on butler/src/app/v2/api/deployments/pipes/git-token-decryption.pipe.ts
> +    const encryptedToken = deploymentRequest.git.token
what if another application(orange stack,a pipeline)  wants to integrate with butler? we will assume that they have access to the encryption key? or they will have to pass by moove to deploy?
only  a question

2021-03-08 17:14 UTC, thallesfreitaszup commented on butler/src/app/v2/operator/use-cases/reconcile-deployment.usecase.ts
> +    const activeComponents = await this.componentRepository.findActiveComponents()
shouldn't we ensure that the active components is only about the workspace that is deploying? what if the same component is registered in another namespace/workspace and with the same butler url?

2021-03-08 19:57 UTC, lucasbfernandes approved these changes

2021-03-08 19:57 UTC, merged