Get all system token
ZupIT/charlescd pull request #964
Opened 2021-03-05 17:46 UTC by pedromcborges

### Request:
> Url: *GET* {{url}}/api/v1/system-token?page=&size=&sort=

### Response:
> Status: *200 OK*

Payload:
json
```
{
    "content": [
        {
            "id": "181d0f08-7867-11eb-85f3-0242c0a50003",
            "name": "system_token",
            "permissions": null,
            "created_at": "2021-02-26T16:16:14.64493Z",
            "revoked_at": "2021-03-03T16:16:14.64493Z",
            "last_used_at": "2021-02-28T16:16:14.64493Z",
            "author": "test@test.com"
        },
        {
            "id": "678dadd2-e043-4e12-ac19-0638042faeca",
            "name": "system_token 2",
            "permissions": null,
            "created_at": "2021-02-26T16:16:14.64493Z",
            "author": "charlesadmin@admin"
        },
    ],
    "page": 0,
    "size": 20,
    "last": true,
    "totalPages": 1
}
```

2021-03-08 18:35 UTC, emiteze requested changes

2021-03-08 18:35 UTC, emiteze commented on gate/internal/repository/system_token_repository.go
> +	var systemToken []models.SystemToken
Acho que systemTokens ficaria melhor, ja que é uma lista

2021-03-08 19:47 UTC, emiteze approved these changes

2021-03-09 18:23 UTC, monicaribeiro approved these changes

2021-03-09 18:23 UTC, merged