Refactor workspace
ZupIT/charlescd pull request #968
Opened 2021-03-05 18:38 UTC by barbararochazup

## Issue Description

Please include a summary of what should be implemented or which problem has been corrected. Please also include relevant motivation and context.

## Solution

Please include a summary of the change and what has been implemented. Please also include relevant motivation and context. List all the dependencies required for this change.

## Results

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

### Request (if appropriate):
> Url: **POST** {{url}}/hello/{{hello-code}}

Payload:
```json
{
    "key" : "value"
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "key" :  "value"
}
```
### Screenshots (if appropriate):

2021-03-11 13:12 UTC, pedroborgeszup requested changes

2021-03-11 13:12 UTC, pedroborgeszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/usergroup/response/UserGroupResponse.kt
>      val users: List<SimpleUserResponse>
To maintain the response pattern, I think should return this value, even if empty

2021-03-11 13:12 UTC, pedroborgeszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/workspace/response/SimpleWorkspaceResponse.kt
> +    val permissions: List<String>,
To maintain the response pattern, I think should return this value, even if empty

2021-03-11 17:27 UTC, luanecavalcantizup commented on ui/src/modules/Users/__tests__/hooks.spec.ts
>  // TODO hooks.spec.tsx to .ts
remove comments

2021-03-11 23:13 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/usergroup/response/UserGroupResponse.kt
>      val users: List<SimpleUserResponse>
Done

2021-03-11 23:13 UTC, barbararochazup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/workspace/response/SimpleWorkspaceResponse.kt
> +    val permissions: List<String>,
Done

2021-03-16 17:08 UTC, luanecavalcantizup submitted a review, later dismissed

2021-03-16 17:49 UTC, pedroborgeszup approved these changes

2021-03-22 14:52 UTC, luanecavalcantizup submitted a review, later dismissed

2021-03-22 14:52 UTC, pedroborgeszup approved these changes

2021-04-08 14:57 UTC, luanecavalcantizup commented on ui/src/core/utils/abilities.ts
> +  console.log('setUserAbilities: isRoot()', isRoot());
remove console.log

2021-04-08 14:59 UTC, luanecavalcantizup approved these changes

2021-04-15 17:24 UTC, pedroborgeszup submitted a review, later dismissed

2021-05-06 12:13 UTC, closed without merging