Moove attach matcher
ZupIT/charlescd pull request #996
Opened 2021-03-15 17:09 UTC by leandrorodrigueszup

## Issue Description

Ao adicionar ou remover um circle matcher do moove, o sistema irá deletar todos os dados do circle matcher, referentes ao workspace corrente.

2021-03-16 13:27 UTC, thallesfreitaszup requested changes

2021-03-16 13:27 UTC, thallesfreitaszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/service/CircleMatcherClientService.kt
> +        circles.forEach { create(it, matcherUri) }
All circles are created as inactive, we should check if the circle have active deployments before creation

2021-03-16 13:27 UTC, thallesfreitaszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/service/CircleMatcherClientService.kt
> +        circles.forEach { create(it, matcherUri) }
if the circle segmentation type  is `SIMPLE_KV` we should use the `createImport` otherwise the circle  will be created as a `REGULAR`

2021-03-16 13:27 UTC, thallesfreitaszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/workspace/impl/PatchWorkspaceInteractorImpl.kt
> +        } catch (exception: Exception) {
cant´t we use a specific exception  when the matcher url is invalid? @leandrorodrigueszup  @emiteze

2021-03-16 13:27 UTC, thallesfreitaszup commented on moove/infrastructure/src/test/groovy/io/charlescd/moove/infrastructure/service/CircleMatcherClientServiceTest.groovy
> +    def "should find the circles from workspace and delete of circle-matcher"() {
```suggestion
    def "should find the circles from workspace and delete at circle-matcher"() {
```

2021-03-16 13:34 UTC, leandrorodrigueszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/service/CircleMatcherClientService.kt
> +        circles.forEach { create(it, matcherUri) }
Ok, we have to check it out, because, everything a circle is created, it is sent to circle-matcher. So checking active deployments its not part of the rules today.

2021-03-16 13:35 UTC, leandrorodrigueszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/service/CircleMatcherClientService.kt
> +        circles.forEach { create(it, matcherUri) }
`if the circle segmentation type is SIMPLE_KV we should use the createImport otherwise the circle will be created as a REGULAR` I'll check it.

2021-03-16 19:48 UTC, emiteze commented on moove/application/src/main/kotlin/io/charlescd/moove/application/workspace/impl/PatchWorkspaceInteractorImpl.kt
> +        } catch (exception: Exception) {
it's kinda hard to predict what kind of exception we had on this integration since everything will came up as FeignException since we don't have nothing particularly handling our feign exceptions or probably http exceptions from java originally (like Unknown Host Exception). I think that would be great if we improves all this error handling on moove (not only here) but I think that since it was just designed that way, I would not link this improvement to @leandrorodrigueszup's PR

2021-03-16 19:51 UTC, emiteze commented on moove/application/src/main/kotlin/io/charlescd/moove/application/workspace/impl/PatchWorkspaceInteractorImpl.kt
> +            }
Thinking about the order of this operations, it makes sense to delete all entries on the current matcher before trying to insert on the new one? Cause if we have a problem inserting these entries on the new matcher, we will lose our keys since it was already deleted from the old one

2021-03-16 19:56 UTC, leandrorodrigueszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/workspace/impl/PatchWorkspaceInteractorImpl.kt
> +            }
We've talked about that. To be sure that everything in the new matcher is brand new, we have to delete that all, and then save everything again. That is the easier way to "sync" the data.

2021-03-16 19:59 UTC, emiteze commented on moove/application/src/main/kotlin/io/charlescd/moove/application/workspace/impl/PatchWorkspaceInteractorImpl.kt
> +        } catch (exception: Exception) {
And also thinking about the migration to the charles core monolith, i think that we can design better our exception handling on that new guy instead of fixing this on moove

2021-03-16 20:06 UTC, thallesfreitaszup commented on moove/application/src/main/kotlin/io/charlescd/moove/application/workspace/impl/PatchWorkspaceInteractorImpl.kt
> +        } catch (exception: Exception) {
Agreed

2021-03-23 17:11 UTC, thallesfreitaszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/JdbcCircleRepository.kt
> +                           TRUE                        AS circle_active
don´t need to do the same for the inactive circles query?

2021-03-23 17:16 UTC, leandrorodrigueszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/JdbcCircleRepository.kt
> +                           TRUE                        AS circle_active
No, because the query is already for active circles. I just ensure that the flag has the right value.

2021-03-23 17:27 UTC, thallesfreitaszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/JdbcCircleRepository.kt
> +                           TRUE                        AS circle_active
I mean do the same on the query for inactive circles on line 355. Update there too to have the "circle_active" on extractor

2021-03-23 17:29 UTC, leandrorodrigueszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/JdbcCircleRepository.kt
> +                           TRUE                        AS circle_active
Oh, I got. I can put 'FALSE' there, but its no necessary. The default is false.

2021-03-23 17:31 UTC, thallesfreitaszup commented on moove/infrastructure/src/main/kotlin/io/charlescd/moove/infrastructure/repository/JdbcCircleRepository.kt
> +                           TRUE                        AS circle_active
Nice!

2021-03-23 17:31 UTC, thallesfreitaszup submitted a review, later dismissed

2021-03-23 19:58 UTC, lucasbfernandes submitted a review, later dismissed

2021-03-25 13:21 UTC, thallesfreitaszup approved these changes

2021-03-25 17:24 UTC, lucasbfernandes approved these changes

2021-04-07 18:11 UTC, merged