Create system token
ZupIT/charlescd pull request #999
Opened 2021-03-16 12:27 UTC by emiteze

## Issue Description

We are developing a new feature and we needed crud operations for new system token entity.

## Solution

Create system token endpoint.

## Results

Ran postman tests.

### Request (if appropriate):
> Url: **POST** {{url}}/api/v1/system-token

Payload:
```json
{
	"name": "New Token",
	"permissions": ["permission1", "permission2", "permission3"],
	"workspaces": ["workspace1", "workspace2"]
}
```
### Response:
> Status: **200 OK**

Payload:
```json
{
    "id": "a0a27a81-aad7-4670-a5f6-1c6e8d0afc30",
    "name": "New Token",
    "permissions": [
        "permission1",
        "permission2",
        "permission3"
    ],
    "workspaces": [
        "workspace1",
        "workspace2"
    ],
    "created_at": "2021-03-15T19:41:16.590104448-03:00",
    "revoked_at": null,
    "last_used_at": null,
    "author": "user@charles"
}
```

> Status: **422 UNPROCESSABLE ENTITY - AUTHORIZATION IS MISSING**

Payload:
```json
{
    "id": "14366f00-bb69-4bdd-8655-2042fe0f75d7",
    "message": "Unable to parse authorization",
    "detail": "token is required",
    "type": "BusinessError",
    "timestamp": "1615897200"
}
```

> Status: **422 UNPROCESSABLE ENTITY - USER NOT FOUND**

Payload:
```json
{
    "id": "e91967e7-8fb0-486d-9a3e-776b719eb497",
    "message": "Unable to find user by email",
    "detail": "user not found",
    "type": "BusinessError",
    "timestamp": "1615897411"
}
```

> Status: **422 UNPROCESSABLE ENTITY - PERMISSIONS NOT FOUND**

Payload:
```json
{
    "id": "127f296e-7596-45f4-829a-0eb63fff7c43",
    "message": "Some permissions were not found",
    "detail": "some permissions were not found",
    "type": "BusinessError",
    "timestamp": "1615897515"
}
```

> Status: **422 UNPROCESSABLE ENTITY - WORKSPACES NOT FOUND**

Payload:
```json
{
    "id": "59afa958-ffc1-45d0-9dcd-0eb20152af0c",
    "message": "Some workspaces were not found",
    "detail": "some workspaces were not found",
    "type": "BusinessError",
    "timestamp": "1615897565"
}
```

> Status: **500 INTERNAL SERVER ERROR - INVALID INPUTS**

Payload:
```json
{
    "id": "5bfde8bc-f748-4221-8d52-006083760e5f",
    "message": "Invalid Inputs",
    "detail": "",
    "type": "",
    "timestamp": "1615897608"
}
```

2021-03-16 14:09 UTC, monicaribeiro requested changes

2021-03-17 21:41 UTC, barbararochazup commented on gate/internal/repository/models/system_token.go
> +	Author      string `gorm:"column:author_email"`
Very nice this!

2021-03-17 21:45 UTC, barbararochazup approved these changes

2021-03-18 19:45 UTC, pedroborgeszup approved these changes

2021-03-19 13:52 UTC, emiteze commented on gate/internal/repository/models/system_token.go
> +	Author      string `gorm:"column:author_email"`
thanks <3

2021-03-22 20:19 UTC, pedroborgeszup requested changes

2021-03-22 20:19 UTC, pedroborgeszup commented on gate/internal/repository/user_repository.go
> +		return false, handleUserError("User not found", "repository.UserRepository.FindByEmail", errors.New("user not found"), logging.NotFoundError)
it should not throw an error, it should return false and null, since in this context not having the user is not an error

2021-03-22 20:19 UTC, pedroborgeszup commented on gate/internal/use_case/system_token/create_system_token.go
> +		return domain.SystemToken{}, logging.NewError("Unable to parse authorization", err, logging.BusinessError, nil, "createSystemToken.Execute")
you should not create a NewError, as you are already receiving a NewError from the repository. Could use a logging.WithOperation(err, "...") for this situation

2021-03-22 20:19 UTC, pedroborgeszup commented on gate/internal/use_case/system_token/create_system_token.go
> +		return domain.SystemToken{}, logging.NewError("Unable to find user by email", err, logging.BusinessError, nil, "createSystemToken.Execute")
you should not create a NewError, as you are already receiving a NewError from the repository. Could use a logging.WithOperation(err, "...") for this situation

2021-03-23 20:48 UTC, monicaribeiro requested changes

2021-03-23 20:48 UTC, monicaribeiro commented on gate/internal/repository/system_token_repository.go
> +			return domain.SystemToken{}, handleSystemTokenError("Token not found", "unit.GetById.First", res.Error, logging.NotFoundError)
```suggestion
			return domain.SystemToken{}, handleSystemTokenError("Token not found", "SystemTokenRepository.GetById", res.Error, logging.NotFoundError)
```

2021-03-23 20:48 UTC, monicaribeiro commented on gate/internal/repository/user_repository.go
> +		return false, handleUserError("User not found", "repository.UserRepository.FindByEmail", errors.New("user not found"), logging.NotFoundError)
```suggestion
		return false, handleUserError("User not found", "UserRepository.FindByEmail", errors.New("user not found"), logging.NotFoundError)
```

2021-03-23 20:48 UTC, monicaribeiro commented on gate/internal/repository/workspace_repository.go
> +		return 0, handleWorkspaceError("Find all workspaces failed", "repository.ExistsByIds.Count", res.Error, logging.NotFoundError)
```suggestion
		return 0, handleWorkspaceError("Find all workspaces failed", "WorkspaceRepository.ExistsByIds", res.Error, logging.NotFoundError)
```

2021-03-23 20:48 UTC, monicaribeiro commented on gate/internal/use_case/system_token/create_system_token.go
> +		return domain.SystemToken{}, logging.NewError("Unable to parse authorization", err, logging.BusinessError, nil, "createSystemToken.Execute")
```suggestion
		return domain.SystemToken{}, logging.NewError("Unable to parse authorization", err, logging.BusinessError, nil, "CreateSystemToken.Execute")
```

2021-03-25 12:49 UTC, pedroborgeszup approved these changes

2021-04-05 13:24 UTC, monicaribeiro approved these changes

2021-04-05 13:25 UTC, merged